/**
 * 台灣夜市大百科：全台 200+ 代表性道地夜市美食資料庫 (Grand Taiwan Night Market Food Encyclopedia)
 * 涵蓋經典主食、酥脆炸物、炭烤燒烤、蒸炊包點、特色麵食、濃郁羹湯煲鍋、冷熱滷味、傳統冰品甜點、手搖飲品
 */

const GRAND_TAIWAN_FOODS = [
    // ========================================================
    // 1. 經典主食與飯類 (Rice Dishes & Classic Staples)
    // ========================================================
    {
        foodName: '經典黑金滷肉飯',
        foodNameEN: 'Classic Taiwanese Braised Pork Rice',
        foodPrice: 40,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '精選黑豬帶皮五花肉細切成條，以古法純釀醬油、紅蔥酥與冰糖慢火煨燉六小時，膠質豐厚黏嘴，澆在熱氣騰騰的冠軍白米飯上，油亮甘醇。',
        foodInfoEN: 'Hand-diced pork belly braised for six hours in aged soy reduction with fried shallots, poured over fragrant steamed rice.',
        calories: 480,
        culturalStory: '滷肉飯是台灣最具國際知名度的庶民國飯，南北作法各具特色。北部多稱滷肉飯重醬香，南部稱肉燥飯微甘帶甜。一碗熱呼呼的黑金滷肉飯是無數台灣人從早餐到宵夜的靈魂慰藉。',
        texture: '肥肉入口即化，瘦肉軟嫩入味，滷汁鹹甜適中帶濃濃膠質黏稠感。',
        ingredients: ['台灣特選帶皮黑豬五花肉', '自製手工紅蔥酥', '西螺古法黑豆蔭油', '冰糖與五香粉', '台梗九號頂級白米'],
        allergens: ['含大豆', '含麩質之穀物'],
        cookingMethod: '先炒糖色與蔥油爆香肉丁，再以小火微沸慢燉六小時直至肉膠完全釋放。',
        bestPairing: '必配一顆滷透入味的五香滷鴨蛋，再搭一碗清甜大骨蘿蔔貢丸湯。',
        priceRange: 'NT$ 35 - 55',
        tags: ['國飯之王', '膠質爆棚', '老字號風味', '百吃不厭']
    },
    {
        foodName: '彰化老擔爌肉飯',
        foodNameEN: 'Changhua Braised Pork Belly on Rice',
        foodPrice: 75,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=800&q=80',
        foodInfo: '精選大塊溫體豬後腿蹄膀肉，以藺草或竹籤穿透定型，在大陶鍋中以甘蔗與陳年老滷長時間文火慢滷，皮Q肉嫩不散開，香濃滑順。',
        foodInfoEN: 'Thick-cut pork knuckle tied with bamboo skewer, slow-braised in sugarcane and dark soy glaze until tender and melt-in-mouth.',
        calories: 620,
        culturalStory: '彰化是全台灣爌肉飯的一級戰區，從清晨到深夜24小時都有排隊名店接力營業。講究皮、脂、肉三層分明，插竹籤慢燉是傳承百年的獨門智慧。',
        texture: '豬皮Q彈有嚼勁，肥肉肥而不膩，瘦肉軟爛多汁不柴口。',
        ingredients: ['台灣溫體豬後腿蹄膀肉', '南投埔里紅甘蔗頭', '古法純釀黑豆醬油', '青蔥與大蒜', '陳年紹興酒'],
        allergens: ['含大豆', '含小麥'],
        cookingMethod: '過水川燙去腥後穿籤，油炸定型再入老滷鍋文火慢熬五小時。',
        bestPairing: '配酸菜、辣炒菜脯，再來一碗龍骨髓湯或豆腐味噌湯。',
        priceRange: 'NT$ 65 - 90',
        tags: ['彰化必吃', '肉控天堂', '三層分明', '24小時傳奇']
    },
    {
        foodName: '古早味筒仔米糕',
        foodNameEN: 'Tube Rice Cake with Savory Pork Topping',
        foodPrice: 50,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '圓糯米拌入自炒蔥油肉燥，填入特製圓筒小鐵罐中高溫蒸熟，倒扣於盤中，淋上甜辣粉紅醬與肉鬆、香菜，米粒軟糯彈牙。',
        foodInfoEN: 'Seasoned glutinous rice steamed in small stainless cylinders, served inverted with sweet pink relish and pork floss.',
        calories: 420,
        culturalStory: '起源於蘇東坡的「盤遊飯」，早期在竹筒中炊蒸，後來演變為鐵筒炊具。米粒吸飽肉汁精華，是台灣各大廟口夜市最經典的傳統米食之一。',
        texture: '糯米軟Q有彈性，肉燥甘醇，配上脆甜小黃瓜絲清爽解膩。',
        ingredients: ['頂級長糯米', '黑豬絞肉', '埔里乾香菇', '金鉤蝦米', '台式甜辣海山醬'],
        allergens: ['含甲殼類蝦', '含大豆', '含麩質'],
        cookingMethod: '糯米先泡水蒸半熟拌炒料，裝筒後再入大蒸籠二次高溫透蒸。',
        bestPairing: '經典絕配為排骨酥湯或四神湯，一乾一湯最為飽足。',
        priceRange: 'NT$ 40 - 60',
        tags: ['廟口經典', '古法蒸炊', '甜辣紅醬', '米食精華']
    },
    {
        foodName: '台南安平現炒蝦仁飯',
        foodNameEN: 'Tainan Anping Fresh Shrimp Rice',
        foodPrice: 70,
        foodType: ['傳統小吃', '海鮮鍋物'],
        foodIcon: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?auto=format&fit=crop&w=800&q=80',
        foodInfo: '每日安平港現撈火燒蝦人工去殼，高溫大火快速爆炒鎖住蝦甜，米飯以濃郁柴魚大骨高湯與蝦汁悶煮入味，粒粒米飯吸飽鮮美海味。',
        foodInfoEN: 'Wild red fire shrimps stir-fried quickly on high heat, served atop rice infused with rich bonito broth and shrimp nectar.',
        calories: 390,
        culturalStory: '日治時期結合日式炊飯與台南在地火燒蝦所創。火燒蝦體積雖小但蝦香濃烈，高湯炊煮的米飯濕潤鮮甜，是台南安平傳承近百年的風雅小吃。',
        texture: '米飯濕潤甘美吸飽蝦香，火燒蝦肉質細嫩彈脆。',
        ingredients: ['台南安平新鮮火燒蝦', '特級柴魚高湯', '自熬豬油紅蔥頭', '壽司米', '青蔥段'],
        allergens: ['含甲殼類蝦', '含大豆'],
        cookingMethod: '大鐵鼎炒香蝦仁起鍋，利用餘汁高湯煨煮米飯，出鍋鋪上蝦仁。',
        bestPairing: '加點一顆半熟油炸鴨蛋，劃破蛋黃拌入蝦仁飯，濃郁倍增。',
        priceRange: 'NT$ 60 - 85',
        tags: ['台南安平', '火燒蝦香', '鮮美高湯', '半熟蛋絕配']
    },
    {
        foodName: '東港野生櫻花蝦炒飯',
        foodNameEN: 'Donggang Sakura Shrimp Fried Rice',
        foodPrice: 110,
        foodType: ['傳統小吃', '海鮮鍋物'],
        foodIcon: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?auto=format&fit=crop&w=800&q=80',
        foodInfo: '屏東東港三寶之一的珍貴野生櫻花蝦，熱油小火炸出酥脆焦香，搭配土雞蛋與隔夜冷飯，大火鐵鼎翻炒出粒粒分明、香氣撲鼻的黃金炒飯。',
        foodInfoEN: 'Rare wild sakura dried shrimps flash-fried crispy, wok-tossed with eggs and rice on roaring flames.',
        calories: 550,
        culturalStory: '全世界僅台灣東港與日本靜岡駿河灣產出珍貴野生櫻花蝦。蝦殼薄脆富含甲殼素與鈣質，夜市熱炒師傅大火翻炒，鑊氣與海味完美交融。',
        texture: '櫻花蝦香酥脆口，米粒乾爽粒粒分明，蛋香蔥香撲鼻。',
        ingredients: ['屏東東港正宗野生櫻花蝦', '台南冷飯', '新鮮農場雞蛋', '青蔥花', '特調胡椒鹽'],
        allergens: ['含甲殼類', '含蛋製品'],
        cookingMethod: '櫻花蝦先煸香瀝油，熱鍋冷油炒散雞蛋與米飯，起鍋前撒櫻花蝦翻炒十秒。',
        bestPairing: '搭配鮮魚蛤蜊薑絲湯或生啤酒，痛快過癮。',
        priceRange: 'NT$ 90 - 130',
        tags: ['東港三寶', '鑊氣炒飯', '酥脆櫻花蝦', '海味無窮']
    },

    // ========================================================
    // 2. 經典小吃與包點煎物 (Iconic Snacks & Pan-Fried Wonders)
    // ========================================================
    {
        foodName: '招牌雙拼綜合煎',
        foodNameEN: 'Deluxe Oyster & Shrimp Omelet',
        foodPrice: 95,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        foodInfo: '嘉義東石肥嫩蚵仔與鮮甜白蝦仁雙倍份量！搭配紅殼土雞蛋與有機小白菜，特調地瓜粉水在大圓鐵板上煎得周圍蕾絲裙邊金黃薄脆，淋上特製雙色紅甜醬。',
        foodInfoEN: 'Double portion of coastal oysters and plump shrimps pan-fried with farm eggs, crunchy batter crust, and sweet chili gravy.',
        calories: 460,
        culturalStory: '台灣夜市小吃公認的代表圖騰！相傳源自鄭成功軍隊糧食短缺時以地瓜粉水煎蚵仔裹腹，經過數百年改良，酥脆粉漿與甜辣海山醬已成全台共通記憶。',
        texture: '外圍蕾絲邊極致香脆，中央粉漿軟糯滑嫩，蚵仔爆汁蝦仁脆彈。',
        ingredients: ['嘉義東石產地直送鮮蚵', '生鮮剝殼大白蝦', '特調紅薯地瓜粉漿', '有機小白菜', '古法甜辣醬'],
        allergens: ['含甲殼類蝦', '含貝類蚵仔', '含蛋製品'],
        cookingMethod: '高溫平底鐵板爆香海鮮，下粉漿慢轉搶酥，打蛋翻面至兩面金黃。',
        bestPairing: '必配一碗生炒花枝羹或清爽冬瓜茶，酸甜解膩。',
        priceRange: 'NT$ 85 - 110',
        tags: ['夜市代表', '海陸雙拼', '蕾絲脆邊', '必點神作']
    },
    {
        foodName: '彰化脆皮炸肉圓',
        foodNameEN: 'Changhua Crispy Deep-Fried Ba-Wan',
        foodPrice: 55,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        foodInfo: '外皮特製粉漿經高溫油炸後呈現如餅乾般的爆酥口感！內餡包入大塊黑豬後腿肉、鮮甜香菇與脆爽竹筍丁，剪開淋上白甜米醬、黑豆醬油與蒜泥。',
        foodInfoEN: 'Iconic Taiwanese meat dumpling with an extra-crispy deep-fried shell, filled with marinated pork chunks, shiitake, and bamboo shoots.',
        calories: 450,
        culturalStory: '彰化肉圓名聞全台，除了傳統低溫油泡作法，新一代「脆皮肉圓」將外皮炸至金黃酥脆發泡，口感外脆內Q，曾創下排隊數小時的狂潮。',
        texture: '外皮咬下去卡滋酥脆，內層依然彈牙Q軟，肉餡扎實多汁。',
        ingredients: ['地瓜粉與在來米漿', '黑豬後腿肉塊', '埔里大香菇', '高山麻竹筍丁', '古法特調白甜醬'],
        allergens: ['含大豆', '含小麥'],
        cookingMethod: '蒸熟定型後投入高溫油鍋大火猛炸，使表皮瞬間起泡爆酥。',
        bestPairing: '搭配店家熬製的大骨清湯或豆腐貢丸湯最對味。',
        priceRange: 'NT$ 50 - 70',
        tags: ['彰化名產', '脆皮卡滋', '雙色米醬', '超強排隊']
    },
    {
        foodName: '台南傳統古早味碗粿',
        foodNameEN: 'Tainan Traditional Savory Steamed Rice Bowl Cake',
        foodPrice: 45,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '在來米漿拌入濃醇黑豬肉燥高湯，注入陶瓷碗中，加入鹹蛋黃、香菇、赤肉塊大火炊蒸，呈現誘人醬色。吃時以小竹籤劃開淋上甘甜蒜蓉醬油膏。',
        foodInfoEN: 'Old-school savory rice cake steamed in porcelain bowls with salted egg yolk, pork, and mushrooms, drizzled with sweet garlic soy glaze.',
        calories: 360,
        culturalStory: '台南麻豆碗粿講究的是「黑碗粿」，米漿預先調入肉燥油蔥，蒸出來色澤深沉、香氣濃烈。用竹籤沿碗緣劃開是台南老一輩吃碗粿的道地儀式感。',
        texture: '米體扎實軟Q富米香，醬汁鹹甜甘美，蒜泥提味辛香。',
        ingredients: ['陳年老在來米磨漿', '黑豬肉燥高湯', '紅土鹹鴨蛋黃', '厚切埔里香菇', '西螺甜油膏'],
        allergens: ['含大豆', '含蛋製品', '含麩質'],
        cookingMethod: '磨米漿調合熟肉燥，注入厚瓷碗大火蒸炊40分鐘熟透。',
        bestPairing: '配上一碗台南虱目魚丸湯或浮水魚羹，就是最滿足的古早味套餐。',
        priceRange: 'NT$ 40 - 55',
        tags: ['台南傳統', '黑碗粿', '竹籤劃吃', '鹹甜甘醇']
    },
    {
        foodName: '傳統台式刈包 (虎咬豬)',
        foodNameEN: 'Taiwanese Pork Belly Gua Bao (Tiger Bites Pig)',
        foodPrice: 65,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '白泡泡幼綿綿的半月型蒸刈包，夾入一整塊滷至透徹紅亮的厚切三層五花肉，鋪上滿滿酸香炒客家酸菜、新鮮香菜，撒上厚厚一層現磨香甜花生糖粉。',
        foodInfoEN: 'Fluffy steamed lotus leaf bun stuffed with thick-cut braised pork belly, pickled mustard greens, fresh cilantro, and sweet peanut powder.',
        calories: 510,
        culturalStory: '刈包外型如虎口咬著大塊豬肉，故俗稱「虎咬豬」，也有「包福包財」的吉慶象徵。五花肉的濃郁脂香被酸菜的中和與花生粉的甜蜜完美包覆，享譽國際被稱作「台式漢堡」。',
        texture: '麵皮蓬鬆鬆軟，五花肉肥嫩油化，酸菜爽脆微酸，花生粉香甜回甘。',
        ingredients: ['手工老麵蒸刈包皮', '特級厚切五花三層肉', '苗栗客家酸菜', '現磨白糖花生粉', '新鮮香菜葉'],
        allergens: ['含花生', '含大豆', '含麩質'],
        cookingMethod: '五花肉文火醬煨三小時，酸菜辣椒油炒去澀，包皮蒸氣保溫現夾。',
        bestPairing: '必配四神豬肚湯或冬瓜茶，酸甜鹹香完美平衡。',
        priceRange: 'NT$ 60 - 80',
        tags: ['台式漢堡', '虎咬豬', '厚切五花', '花生粉香']
    },
    {
        foodName: '新竹城隍廟紅糟肉圓',
        foodNameEN: 'Hsinchu Red Yeast Pork Ba-Wan',
        foodPrice: 50,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        foodInfo: '新竹特有傳統紅糟肉圓！半透明外皮微厚Q軟，內餡以天然紅麴糯米糟醃漬黑豬胛心肉，拌入大量脆綠青蔥，蒸煮後油泡，淋上特製雙醬，風味獨特。',
        foodInfoEN: 'Hsinchu style steamed and gently fried tapioca dumpling filled with red-yeast fermented pork and fresh scallions.',
        calories: 380,
        culturalStory: '新竹肉圓的最大特色就是「紅糟肉餡」與「蔥花」，鮮紅艷麗的紅糟散發自然米酒發酵香氣，已有百餘年歷史，為城隍廟夜市必吃經典。',
        texture: '外皮Q彈有嚼勁，紅糟肉鮮甜帶酒香蔥香。',
        ingredients: ['地瓜粉與太白粉', '天然紅糟醃黑豬肉', '新鮮青蔥段', '新竹傳統雙色甜辣醬'],
        allergens: ['含大豆', '含小麥'],
        cookingMethod: '蒸籠蒸透定型，再浸入溫熱油鍋微火保溫油泡出Q勁。',
        bestPairing: '配新竹大摃丸湯，享受純樸的新竹在地古早味。',
        priceRange: 'NT$ 45 - 60',
        tags: ['新竹特色', '紅糟發酵', '青蔥肉餡', '百年傳承']
    },

    // ========================================================
    // 3. 特色麵食與冬粉羹 (Noodles & Soupy Noodles)
    // ========================================================
    {
        foodName: '經典紅燒半筋半肉牛肉麵',
        foodNameEN: 'Taiwan Braised Beef Shank & Tendon Noodles',
        foodPrice: 180,
        foodType: ['特色麵食', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
        foodInfo: '精選澳洲牛腱心與牛蹄筋，與牛大骨、豆瓣醬、洋蔥、番茄與十多味中藥滷包慢火燉熬十二小時，湯頭紅亮甘美濃郁，搭配手工刀削粗麵與酸菜。',
        foodInfoEN: 'Tender braised beef shank and gelatinous tendon in a rich, deeply spiced beef bone broth with chewy hand-pulled noodles and pickled mustard.',
        calories: 680,
        culturalStory: '誕生於台灣眷村的老兵鄉愁料理，融合四川豆瓣醬與台灣大骨熬湯工法，如今已躍升為代表台灣的頂級代表性國食，每年台北牛肉麵節吸引全球老饕。',
        texture: '牛腱肉酥軟帶汁，牛筋晶瑩軟糯入口即化，麵條勁道彈牙。',
        ingredients: ['澳洲頂級牛腱心', '牛蹄筋', '牛大骨熬製濃湯', '岡山辣豆瓣醬', '手工拉麵', '老壇酸菜'],
        allergens: ['含大豆', '含小麥', '含牛製品'],
        cookingMethod: '牛骨先烤後熬出白湯，牛肉炒醬入味後轉慢火燜燉至極致軟爛。',
        bestPairing: '必加一匙牛油與特炒酸菜，配一杯冰涼無糖四季春青茶解膩。',
        priceRange: 'NT$ 160 - 220',
        tags: ['台灣國食', '半筋半肉', '慢火老湯', '刀削勁道']
    },
    {
        foodName: '台南度小月正宗擔仔麵',
        foodNameEN: 'Tainan Du Xiao Yue Danzai Noodles',
        foodPrice: 60,
        foodType: ['特色麵食', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
        foodInfo: '小碗精緻！油麵川燙後盛碗，注入慢火煨煮的鮮甜蝦頭大骨高湯，淋上一大勺祖傳肉燥、一顆剝殼甜蝦、香菜與蒜泥，淋上一滴五印烏醋，鮮香精緻。',
        foodInfoEN: 'Petite bowl of springy noodles in sweet shrimp and pork broth, crowned with slow-simmered pork gravy, fresh prawn, garlic, and vinegar.',
        calories: 320,
        culturalStory: '創立於清光緒年間，原是漁民在颱風「度小月」無法出海捕魚時挑擔賣麵維生，因而得名。至今已有百餘年歷史，是台灣精緻庶民小吃的代表。',
        texture: '油麵彈牙順滑，湯頭蝦香濃縮清甜，肉燥鹹香提味。',
        ingredients: ['傳統黃油麵', '鮮甜海蝦頭熬製高湯', '百年祖傳紅蔥肉燥', '熟甜白蝦一尾', '五印香醋與蒜泥'],
        allergens: ['含甲殼類蝦', '含大豆', '含小麥'],
        cookingMethod: '竹製麵杓快煮麵條甩乾，注入滾燙蝦骨高湯，淋肉燥點烏醋。',
        bestPairing: '可搭配台南黃金炸蝦捲或炸蚵捲，品嚐府城古雅風味。',
        priceRange: 'NT$ 50 - 75',
        tags: ['百年度小月', '府城精緻', '蝦頭高湯', '祖傳肉燥']
    },
    {
        foodName: '台南大火快炒鱔魚意麵',
        foodNameEN: 'Tainan Sizzling Wok-Fried Eel with Crispy E-Noodles',
        foodPrice: 120,
        foodType: ['特色麵食', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
        foodInfo: '高溫猛火大鼎快炒！新鮮生鱔魚切片在數百度鍋氣中大火翻炒二十秒，加入洋蔥、洋菇、蒜碎與台南酸甜黑醋醬，意麵油炸後吸飽濃稠酸甜羹汁，脆嫩彈牙。',
        foodInfoEN: 'Fresh swamp eel flash-seared over roaring wok fire with onions and sweet black vinegar reduction, served over deep-fried egg noodles.',
        calories: 520,
        culturalStory: '炒鱔魚意麵考驗的是師傅「二十秒大火出鍋」的極致鑊氣功夫。火光沖天的翻鍋技術鎖住鱔魚脆度，酸酸甜甜的勾芡羹汁更是標準台南味。',
        texture: '鱔魚片極致爽脆帶彈性，炸意麵吸飽酸甜醬汁軟中帶微Q，鑊氣濃烈。',
        ingredients: ['新鮮活體現宰黃鱔魚', '台南油炸雞蛋意麵', '新鮮洋蔥絲與蔥段', '鎮江香醋與烏醋', '古早味二砂糖'],
        allergens: ['含魚類', '含蛋製品', '含小麥'],
        cookingMethod: '鼓風爐極限高溫爆炒洋蔥鱔魚，下調料勾薄芡，淋在熱燙意麵上。',
        bestPairing: '搭配一碗當歸羊肉湯或冬瓜清茶，完美解膩。',
        priceRange: 'NT$ 110 - 150',
        tags: ['極限鑊氣', '鱔魚脆爽', '酸甜府城', '大鼎快炒']
    },
    {
        foodName: '東發號古法大腸蚵仔麵線',
        foodNameEN: 'Traditional Oyster & Braised Pork Intestine Vermicelli',
        foodPrice: 70,
        foodType: ['特色麵食', '傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
        foodInfo: '堅持不勾重芡的清甜古法！紅麵線以大骨與柴魚、小魚乾慢熬清湯，大腸以中藥滷至軟Q入味，嘉義東石鮮蚵裹薄粉川燙，加入蒜泥、烏醋與特製辣椒油。',
        foodInfoEN: 'Red thread vermicelli simmered in clean bonito fish broth, topped with tender braised pork intestines and plump poached oysters.',
        calories: 380,
        culturalStory: '台灣夜市隨處可見的經典流動小吃。手工紅麵線久煮不爛，早期為農忙時隨手可煮的點心，如今大腸與蚵仔的雙料搭配成為無敵宵夜經典。',
        texture: '麵線滑順軟潤，大腸Q嫩入味無腥味，蚵仔爆漿鮮甜。',
        ingredients: ['手工日曬紅麵線', '嘉義東石鮮蚵', '中藥老滷豬大腸', '柴魚小魚乾高湯', '現磨大蒜泥與烏醋'],
        allergens: ['含貝類蚵仔', '含大豆', '含小麥'],
        cookingMethod: '高湯沸騰煮透紅麵線，保溫慢煨，現點現盛並鋪上大腸與蚵仔。',
        bestPairing: '加一匙特製生炒辣椒油，配一份脆皮臭豆腐，堪稱夜市絕配組合。',
        priceRange: 'NT$ 60 - 85',
        tags: ['廟口流傳', '手工紅麵線', '鮮蚵大腸', '蒜香烏醋']
    },
    {
        foodName: '澎湖鮮甜小卷小管麵線',
        foodNameEN: 'Penghu Fresh Baby Squid Vermicelli Soup',
        foodPrice: 120,
        foodType: ['特色麵食', '海鮮鍋物'],
        foodIcon: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?auto=format&fit=crop&w=800&q=80',
        foodInfo: '澎湖產地直送生鮮透亮小卷！以整尾現撈小卷入大骨高湯快速汆燙，搭配澎湖西衛手工日曬白麵線，湯頭鮮甜自然，撒上薑絲、蔥花與白胡椒，極致海鮮原味。',
        foodInfoEN: 'Whole fresh wild-caught baby squid flash-cooked in sweet broth with sun-dried Penghu vermicelli, ginger, and scallions.',
        calories: 360,
        culturalStory: '澎湖夏季盛產小管，夜間漁船以集魚燈捕撈。澎湖傳統做法就是簡單清燙小管，利用澎湖天然海風日曬的鹹味白麵線，完全不加味精就鮮甜破表。',
        texture: '小管肉質脆嫩彈牙咬下爆汁，手工麵線細緻滑順不軟爛。',
        ingredients: ['澎湖野生現撈生鮮小管', '澎湖西衛手工日曬麵線', '新鮮老薑絲', '特級白胡椒粉', '大骨蔬菜清湯'],
        allergens: ['含軟體動物小管', '含小麥'],
        cookingMethod: '滾水煮透麵線撈起，熱高湯燙熟生小管整尾鋪上，撒薑絲即成。',
        bestPairing: '搭配一份澎湖花枝丸或海菜煎餅，濃郁海島滋味。',
        priceRange: 'NT$ 100 - 150',
        tags: ['澎湖直送', '生鮮小管', '日曬麵線', '極致鮮甜']
    },

    // ========================================================
    // 4. 酥脆炸物天花板 (Crispy Fried Street Classics)
    // ========================================================
    {
        foodName: '深海酥炸特大魷魚圈',
        foodNameEN: 'Crispy Deep-Fried Colossal Squid Rings',
        foodPrice: 120,
        foodType: ['炸物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
        foodInfo: '特選深海巨大鮮魷魚厚切成圈，以大蒜、米酒與五香料醃漬，裹上特調酥脆外衣高溫油炸，起鍋瀝油甩脂，撒上香濃九層塔、椒鹽粉與洋蔥絲。',
        foodInfoEN: 'Colossal deep-sea squid cut into thick rings, dredged in seasoned flour and fried crispy with fresh basil leaves.',
        calories: 450,
        culturalStory: '近年在全台各大夜市席捲風潮的霸氣海味炸物，巨大的份量與厚切的咀嚼感，成為觀光客逛夜市人手一盒的超人氣炸物名角。',
        texture: '外皮極致酥脆卡滋，魷魚肉厚實飽滿、Q彈多汁帶有海味甘甜。',
        ingredients: ['遠洋急凍深海巨型鮮魷魚', '新鮮九層塔葉', '自製中藥胡椒鹽', '蒜末與洋蔥碎', '特調酥炸粉漿'],
        allergens: ['含軟體動物', '含麩質'],
        cookingMethod: '大火高溫油炸90秒定型搶酥，起鍋前下九層塔爆香甩油。',
        bestPairing: '必配一杯冰涼現打檸檬綠茶或生啤酒，解熱消暑。',
        priceRange: 'NT$ 100 - 140',
        tags: ['夜市爆款', '厚切魷魚', '九層塔香', '外酥內彈']
    },
    {
        foodName: '基隆廟口手工現炸天婦羅',
        foodNameEN: 'Keelung Hand-Shaped Fried Fish Cake (Tianpu-luo)',
        foodPrice: 50,
        foodType: ['炸物', '傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
        foodInfo: '每天現打上等新鮮旗魚漿與鯊魚漿，師傅在油鍋旁手捏成片狀投入沸油中，炸得金黃蓬鬆，剪開配上醃漬酸甜脆口小黃瓜片，淋上招牌味噌甜辣醬。',
        foodInfoEN: 'Hand-formed freshly ground sailfish paste fried golden puffed, served with sweet pickled cucumbers and red miso glaze.',
        calories: 330,
        culturalStory: '源自日式甜不辣（Tempura），但基隆廟口發揚光大為「純魚漿現場手捏現炸」，充滿天然海魚彈性與焦香，已是廟口夜市最長壽的老攤傳奇。',
        texture: '剛起鍋外皮微焦酥香，內層彈牙扎實，魚香濃郁無粉感。',
        ingredients: ['新鮮生鮮旗魚漿', '自製醃糖醋小黃瓜薄片', '古法特調味噌甜辣紅醬', '純白胡椒粉'],
        allergens: ['含魚類', '含大豆'],
        cookingMethod: '新鮮生魚漿手捏下鍋，低溫炸透浮起，高溫搶酥撈出剪塊。',
        bestPairing: '搭配廟口古法肉羹湯，是逛廟口夜市第一攤的不敗首選。',
        priceRange: 'NT$ 45 - 60',
        tags: ['基隆廟口', '純旗魚漿', '手捏現炸', '酸甜小黃瓜']
    },
    {
        foodName: '古法蒜香紅糟排骨酥',
        foodNameEN: 'Traditional Garlic & Red Yeast Spare Ribs',
        foodPrice: 80,
        foodType: ['炸物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
        foodInfo: '嚴選軟嫩豬軟骨排骨肉切丁，以雲林蒜泥、天然紅麴與秘製十三香醃漬24小時，裹薄粉高溫炸至赤褐酥脆，肉香骨脆，每一口都是濃郁蒜香。',
        foodInfoEN: 'Tender pork riblets with soft cartilage marinated 24h in garlic and red yeast, deep-fried until richly brown and fragrant.',
        calories: 490,
        culturalStory: '排骨酥是台灣極具歷史的宴席與夜市小吃，可乾吃亦可入冬瓜湯蒸煮成「排骨酥湯」。外酥肉嫩帶軟骨，是老饕的最愛。',
        texture: '外皮薄脆酥香，肉質軟嫩帶有Q脆軟骨嚼勁，蒜香入骨。',
        ingredients: ['溫體豬軟骨小排', '雲林產地生蒜蓉', '天然紅糟與冰糖', '純釀米酒與醬油', '特級甘藷粉'],
        allergens: ['含大豆', '含小麥'],
        cookingMethod: '厚料低溫醃製入味，低溫油炸熟透，起鍋前高溫逼油上色。',
        bestPairing: '直接撒椒鹽乾吃，或搭配一杯冬瓜山粉圓檸檬露。',
        priceRange: 'NT$ 70 - 100',
        tags: ['蒜香撲鼻', '軟骨Q脆', '紅糟入味', '乾吃燉湯皆美']
    },
    {
        foodName: '老台北香酥炸臭豆腐',
        foodNameEN: 'Taipei Crispy Stinky Tofu with Pickled Cabbage',
        foodPrice: 65,
        foodType: ['炸物', '傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?auto=format&fit=crop&w=800&q=80',
        foodInfo: '純天然莧菜發酵臭豆腐，大油鍋雙重油炸至外殼如同餅乾般金黃香脆，中心戳洞灌入大量生蒜泥醬油膏與香油，配上酸甜冰涼的台式爽脆高麗菜泡菜。',
        foodInfoEN: 'Naturally fermented tofu cubes double-fried to blistered crunchy perfection, spiked with garlic sauce and sweet pickled cabbage.',
        calories: 420,
        culturalStory: '台灣夜市聞名全球的靈魂之味！聞之奇臭、入口極香。金黃豆腐外殼在齒間爆開，孔洞中吸飽蒜泥醬汁，搭配解膩泡菜，是夜市不可動搖的人氣冠軍。',
        texture: '外皮極度香脆發泡，內部豆腐軟嫩如蜂巢飽吸醬汁，泡菜清脆多汁。',
        ingredients: ['天然莧菜汁發酵非基改板豆腐', '手工醃製酸甜高麗菜泡菜', '雲林大蒜泥', '自熬甘甜蒜蓉醬油膏', '純辣油'],
        allergens: ['含大豆', '含小麥'],
        cookingMethod: '低溫鍋炸熟定型，轉高溫大火油炸至表皮金黃酥脆泡開。',
        bestPairing: '必點一碗麻辣鴨血湯或蚵仔麵線，組成台灣夜市鐵三角。',
        priceRange: 'NT$ 55 - 80',
        tags: ['夜市靈魂', '外酥內嫩', '爆汁蒜蓉', '台式酸甜泡菜']
    },

    // ========================================================
    // 5. 炭烤燒烤串燒 (Charcoal Flame & Skewer Wonders)
    // ========================================================
    {
        foodName: '新疆孜然現烤羊肉串',
        foodNameEN: 'Xinjiang Cumin Spiced Charcoal Lamb Skewers',
        foodPrice: 40,
        foodType: ['烤物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '嚴選紐西蘭優質小羔羊前腿肉，肥瘦相間切塊穿串，炭火高溫翻滾烤出羊脂香，猛撒新疆純正大粒孜然與特級辣椒粉，羶味全消，焦香撲鼻。',
        foodInfoEN: 'Tender baby lamb shoulder chunks skewered with alternating fat and lean, roasted over live coals and crusted with cumin and chili.',
        calories: 280,
        culturalStory: '夜市燒烤街不可或缺的異國風味小吃，師傅站在炭火前扇動長烤爐，煙霧與孜然香氣在夜市飄散數百公尺，是夜貓族配酒首選。',
        texture: '羊肉焦香外脆，油脂咬下爆汁，肉質軟嫩帶孜然濃烈香氣。',
        ingredients: ['紐西蘭草飼小羔羊前腿肉', '純天然大粒生孜然籽', '特調五香辣椒粉', '粗海鹽', '純白芝麻'],
        allergens: ['含芝麻', '含牛羊製品'],
        cookingMethod: '紅外線炭火高溫快速炙烤，羊脂滴落炭火引發焦香，撒粉提味。',
        bestPairing: '一口烤羊肉串配上一口冰鎮生啤酒或酸甜酸梅湯，無比暢快。',
        priceRange: 'NT$ 35 - 50',
        tags: ['炭香四溢', '新疆孜然', '小羔羊肉', '宵夜下酒']
    },
    {
        foodName: '炭烤澎湖帶殼鮮活生蠔',
        foodNameEN: 'Penghu Charcoal Grilled Whole Oysters in Shell',
        foodPrice: 120,
        foodType: ['烤物', '海鮮鍋物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?auto=format&fit=crop&w=800&q=80',
        foodInfo: '澎湖無污染海域現採鮮活生蠔！整顆帶厚殼置於炭火爐上現烤，高溫讓蠔殼微開爆出天然鮮美海水鹹香，生蠔肉飽滿肥厚如牛奶般滑嫩，滴上一滴檸檬汁即可享用。',
        foodInfoEN: 'Fresh live oysters grilled in their whole shells over open coals, plump and juicy with sea brine, finished with a squeeze of fresh lemon.',
        calories: 160,
        culturalStory: '澎湖海水鹹度高、海流湍急，產出的生蠔粒粒飽滿肥美、無腥味。近年夜市引進一整盤現烤生蠔，成為高CP值海鮮排隊代表。',
        texture: '生蠔肉滑嫩如布丁爆汁，天然海味鹹甜甘醇，鮮美無匹。',
        ingredients: ['澎湖外海產地直送鮮活帶殼生蠔', '新鮮綠檸檬角', '自製芥末五味醬', '蒜蓉辣椒醬'],
        allergens: ['含貝類牡蠣'],
        cookingMethod: '木炭平鋪均勻炙烤，待殼身開縫溢出湯汁即可撥開食用。',
        bestPairing: '擠檸檬原汁品嚐原味，或搭配芥末醬油，絕妙無比。',
        priceRange: 'NT$ 100 - 150',
        tags: ['產地直送', '鮮甜多汁', '海中牛奶', '原汁原味']
    },
    {
        foodName: '蒜蓉炙燒大扇貝',
        foodNameEN: 'Flame-Torched Giant Scallop with Garlic & Glass Noodles',
        foodPrice: 100,
        foodType: ['烤物', '海鮮鍋物'],
        foodIcon: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?auto=format&fit=crop&w=800&q=80',
        foodInfo: '巨大厚貝殼上鋪滿吸汁綠豆冬粉與鮮甜扇貝肉，鋪上大匙慢火爆香金銀蒜蓉醬與青蔥絲，噴槍高溫炙燒逼出焦香，鮮汁沸騰誘人。',
        foodInfoEN: 'Jumbo scallop on half shell baked with garlic butter sauce, vermicelli glass noodles, scallions, and chili shreds.',
        calories: 220,
        culturalStory: '將港式海鮮蒸扇貝與夜市鐵板炙燒結合的創意小吃，冬粉吸滿扇貝滴落的精華原汁，蒜香濃烈，是海鮮愛好者的必訪打卡美食。',
        texture: '扇貝肉絲絲厚實Q嫩，冬粉吸飽鮮湯滑順入味，蒜香極度濃郁。',
        ingredients: ['帶殼厚肉鮮大扇貝', '特選細綠豆冬粉', '手工煸香金蒜碎與生蒜蓉', '青蔥絲', '海鮮甘醇醬油露'],
        allergens: ['含軟體貝類', '含大豆'],
        cookingMethod: '先炭烤貝殼，鋪蒜蓉冬粉，最後以高溫火槍炙燒上色提香。',
        bestPairing: '搭配鮮切水果茶或甘蔗青茶，甘醇解膩。',
        priceRange: 'NT$ 80 - 120',
        tags: ['炙燒海鮮', '蒜香冬粉', '巨大扇貝', '打卡必備']
    },
    {
        foodName: '七里香炭烤雞屁股串',
        foodNameEN: 'Charcoal Roasted Chicken Tail (Seven-Mile Fragrance)',
        foodPrice: 40,
        foodType: ['烤物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '處理極致乾淨無腥味的嚴選雞尾肉，先滷透入味後再上炭火高溫逼出多餘油脂，外皮烤至金黃微焦發脆，刷上秘製甘醇烤肉醬，脂香迷人。',
        foodInfoEN: 'Chicken tails meticulously trimmed and braised, then grilled over open flames until the skin renders crispy and bursting with flavor.',
        calories: 320,
        culturalStory: '台灣夜市戲稱雞屁股為「七里香」，意指炭烤香氣能飄散七里之外。經過去腺與滷透雙重工序，油脂香濃而不油膩，是老饕專屬的隱藏美味。',
        texture: '外皮焦脆酥香，內部油脂如奶油般滑嫩融化，鹹甜焦香。',
        ingredients: ['特選去腺溫體雞尾肉', '中藥甘蔗老滷汁', '祖傳焦糖蜜汁烤肉醬', '特級胡椒鹽', '白芝麻粒'],
        allergens: ['含大豆', '含小麥', '含芝麻'],
        cookingMethod: '老滷文火先煨半小時，穿串上炭火大火翻烤逼脂刷醬。',
        bestPairing: '搭配一罐冰涼生啤酒，是深夜最罪惡卻最幸福的享受。',
        priceRange: 'NT$ 35 - 50',
        tags: ['七里香', '焦脆爆脂', '夜市老饕', '下酒神物']
    },

    // ========================================================
    // 6. 濃郁羹湯、煲鍋與藥膳 (Warming Soups, Stews & Claypots)
    // ========================================================
    {
        foodName: '府城現沖溫體牛肉湯',
        foodNameEN: 'Tainan Fresh Cut Warm Beef Soup',
        foodPrice: 120,
        foodType: ['傳統小吃', '海鮮鍋物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=800&q=80',
        foodInfo: '台南清晨善化牛墟直送新鮮溫體黃牛肉！師傅刀工厚切生牛肉片入碗，滾燙牛大骨、洋蔥與蔬果高湯直接淋下，牛肉瞬間燙至粉嫩五分熟，湯甜肉嫩。',
        foodInfoEN: 'Raw fresh warm beef hand-sliced thin in bowl, flash-cooked by pouring boiling bone and vegetable broth directly over it.',
        calories: 290,
        culturalStory: '台南最具代表性的飲食神話。每天凌晨由善化屠宰場專車直送尚未進冷藏的溫體牛，肉質保有酵素與水分，以高湯現淋現吃，鮮度天下無雙。',
        texture: '牛肉呈現嬌嫩粉紅色，肉質軟嫩至極鮮甜無比，高湯清甜回甘。',
        ingredients: ['台南善化直送溫體黃牛里肌肉', '牛大骨牛腩蔬果熬製高湯', '新鮮老薑絲', '古法甜醬油膏與豆瓣醬'],
        allergens: ['含大豆', '含牛製品'],
        cookingMethod: '生肉鋪碗，滾水牛骨清湯一口氣衝淋入碗，利用餘溫燙至五分熟。',
        bestPairing: '夾嫩薑絲沾台南甜醬油膏與辣豆瓣醬，配一碗肉燥飯是標準台南早餐。',
        priceRange: 'NT$ 110 - 150',
        tags: ['台南神話', '溫體黃牛', '現沖五分熟', '清甜甘醇']
    },
    {
        foodName: '彰化正宗古法四神豬腸湯',
        foodNameEN: 'Four Herbal Tonic Soup with Tender Pork Intestine',
        foodPrice: 65,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=800&q=80',
        foodInfo: '遵循古法使用淮山、芡實、蓮子與茯苓四味漢方溫補藥材，搭配慢火熬煮的大量薏仁與去油豬小腸，湯色乳白溫潤，滴入數滴當歸人參藥酒，香氣沁脾。',
        foodInfoEN: 'Classic Chinese herbal restorative soup brewed with Job’s tears, lotus seeds, Chinese yam, and tender braised pork intestines.',
        calories: 310,
        culturalStory: '相傳乾隆皇帝下江南時隨行重臣舟車勞頓，以四味中藥燉煮豬肚痊癒，賜名「四臣湯」，民間諧音為「四神湯」。是台灣一年四季溫脾健胃的養生名湯。',
        texture: '豬小腸軟嫩帶Q無腥味，薏仁綿密軟糯，湯頭清雅甘甜帶藥酒香。',
        ingredients: ['台灣新鮮豬小腸', '大顆軟糯薏仁', '蓮子與淮山芡實', '大骨高湯', '特調當歸枸杞藥酒'],
        allergens: ['含大豆'],
        cookingMethod: '豬腸麵粉鹽巴揉洗乾淨，與中藥材入大骨湯慢火燉煮三小時。',
        bestPairing: '搭配肉圓、刈包或油飯，是台灣夜市街頭最和諧的養生組合。',
        priceRange: 'NT$ 55 - 75',
        tags: ['溫補養生', '古法四神', '豬腸軟Q', '當歸藥酒']
    },
    {
        foodName: '台南七股無刺虱目魚肚湯',
        foodNameEN: 'Tainan Chigu Boneless Milkfish Belly Soup',
        foodPrice: 110,
        foodType: ['海鮮鍋物', '傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?auto=format&fit=crop&w=800&q=80',
        foodInfo: '台南七股純海水養殖新鮮虱目魚！人工精細挑刺，整片肥厚魚肚與大量薑絲入清湯快煮，銀白魚皮富含豐富魚油與膠原蛋白，湯頭清甜無比。',
        foodInfoEN: 'Whole fresh deboned milkfish belly poached quickly with ginger shreds in clear fish broth, rich in omega-3 and collagen.',
        calories: 340,
        culturalStory: '虱目魚是台南的「市魚」，相傳鄭成功抵台時向漁民詢問此魚何名，漁民誤聽為「國姓爺賜名」，故又稱「國姓魚」。海水養殖無土味，魚肚油脂豐腴。',
        texture: '魚肚油脂層如果凍般滑嫩融化，魚肉細緻清甜，薑絲清爽提味。',
        ingredients: ['台南七股產地直銷無刺虱目魚肚', '新鮮老薑絲', '青蔥花', '特級純白胡椒粉', '魚骨蔬菜甘醇高湯'],
        allergens: ['含魚類'],
        cookingMethod: '魚高湯大火滾沸，下整片無刺魚肚與薑絲燙煮三分鐘至魚肚熟嫩。',
        bestPairing: '沾哇沙米芥末醬油膏，搭配一碗古早味肉燥飯，地道台南風情。',
        priceRange: 'NT$ 95 - 130',
        tags: ['台南市魚', '無刺魚肚', '膠原魚油', '清爽鮮甜']
    },

    // ========================================================
    // 7. 滷味小菜與老字號熟食 (Braised & Street Delicacies)
    // ========================================================
    {
        foodName: '東山黑糖蜜汁鴨頭',
        foodNameEN: 'Dongshan Brown Sugar Honey Braised Duck Head',
        foodPrice: 60,
        foodType: ['傳統小吃', '炸物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=800&q=80',
        foodInfo: '台南東山創始名產！先以天然黑糖、麥芽糖與數十味中藥老滷汁將新鮮鴨頭與鴨脖長時間慢熬入味，再投入熱油鍋高溫酥炸，外皮焦糖酥脆、骨肉酥香入味。',
        foodInfoEN: 'Heritage Dongshan delicacy: duck head braised in brown sugar and herbs, then flash-fried to caramelized crispy perfection.',
        calories: 380,
        culturalStory: '起源於台南東山鄉，獨創「先滷後炸」的繁複工序，黑糖甜香與中藥甘醇在油炸過程中梅納反應焦糖化，連鴨骨頭都能嚼碎吞下，香甜酥口。',
        texture: '外皮焦甜酥香，骨髓酥軟入味，鴨脖肉絲絲甜潤耐嚼。',
        ingredients: ['新鮮合格肉鴨頭與鴨脖', '台南東山天然純黑糖', '麥芽糖與冰糖', '漢方十三香老滷', '純胡椒鹽'],
        allergens: ['含大豆', '含小麥'],
        cookingMethod: '老滷鍋微沸慢熬三小時入色入味，撈出瀝乾入高溫油鍋搶炸出焦香。',
        bestPairing: '搭配東山甜不辣、鴨翅與豆干，再來一杯冰鎮甘蔗青茶。',
        priceRange: 'NT$ 50 - 75',
        tags: ['台南東山', '先滷後炸', '黑糖焦香', '骨肉皆酥']
    },
    {
        foodName: '萬華紅花去骨麻辣鹽水雞',
        foodNameEN: 'Wanhua Boneless Spicy Salted Chicken with Fresh Greens',
        foodPrice: 150,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '放山土公雞低溫鹽水熟化，手工快刀去骨切丁，加入高山高麗菜、玉米筍、小黃瓜與米血，拌入特製花椒辣油、純雞湯汁、胡椒鹽與大量生蒜碎，香麻脆爽。',
        foodInfoEN: 'Hand-deboned tender salted chicken tossed with cold mountain vegetables, Sichuan peppercorn oil, garlic, and savory chicken broth.',
        calories: 340,
        culturalStory: '夜市宵夜極受年輕族群喜愛的輕食炸街美味。冷食拌醬的作法低熱量且清爽，滿滿的新鮮時蔬與麻辣醬汁讓逛夜市無負擔又大飽口福。',
        texture: '雞皮極脆爽彈，雞肉扎實多汁，鮮蔬爽脆微辛，花椒香麻開胃。',
        ingredients: ['去骨放山鹽水土雞', '高山脆甜高麗菜', '鮮嫩玉米筍', '大紅袍花椒辣油', '濃郁純雞高湯露', '生蒜蓉'],
        allergens: ['含大豆', '含芝麻'],
        cookingMethod: '低溫浸滷去骨冷藏，現點現剪，大不鏽鋼鋼盆以特製醬汁快速手拌。',
        bestPairing: '配無糖冷泡高山烏龍茶或新鮮檸檬汁，極致清爽。',
        priceRange: 'NT$ 130 - 180',
        tags: ['去骨多汁', '花椒麻香', '高纖時蔬', '宵夜輕食首選']
    },
    {
        foodName: '東海蓮心冰黑糖雞爪凍',
        foodNameEN: 'Taichung Tunghai Lotus Savory Braised Chicken Feet Jelly',
        foodPrice: 45,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=800&q=80',
        foodInfo: '台中東海商圈傳奇小吃！手工細心剪除雞爪趾甲，以古法黑糖、甘草與醬油文火慢滷四小時，冷藏後膠原蛋白自然凝結如果凍，骨肉輕輕一吸即可分離。',
        foodInfoEN: 'Famous Taichung chicken feet simmered in brown sugar soy broth, chilled to form a savory collagen jelly coating on bone and skin.',
        calories: 210,
        culturalStory: '發跡於台中東海大學旁，原本只是佐冰品的小食，沒想到其獨特的「皮凍膠質」與香濃醬香引爆全台團購熱潮，成為台中最具代表性的伴手禮。',
        texture: '冰涼爽口，膠質如果凍般滑嫩Q彈，中藥醬香深入骨髓。',
        ingredients: ['新鮮嚴選大雞爪', '天然黑糖與麥芽', '甘草與八角肉桂', '純釀醬油', '特級麻油'],
        allergens: ['含大豆', '含小麥'],
        cookingMethod: '修剪指甲川燙，入黑糖老滷細火慢煨，冷藏凝結出豐富天然皮凍。',
        bestPairing: '一口雞爪凍一口綠豆沙牛乳，是台中夏日最爽快的吃法。',
        priceRange: 'NT$ 40 - 60',
        tags: ['台中傳奇', '天然膠原凍', '一吸即脫骨', '冰涼解饞']
    },

    // ========================================================
    // 8. 經典甜品與古早味冰品 (Traditional Desserts & Shaved Ice)
    // ========================================================
    {
        foodName: '宜蘭花生捲冰淇淋 (現刨花生糖)',
        foodNameEN: 'Yilan Peanut Shaving Ice Cream Roll with Cilantro',
        foodPrice: 50,
        foodType: ['甜點飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        foodInfo: '宜蘭頭城傳統代表甜點！薄透潤餅皮上以木工刨刀現場刨出堆疊如山的花生麥芽糖粉，放上兩大球古早味叭噗冰淇淋（芋頭、鳳梨），撒上新鮮現摘香菜捲起，鹹甜冰涼驚為天人。',
        foodInfoEN: 'Spring roll crepe loaded with hand-planed malted peanut candy shavings, artisanal taro/pineapple ice cream scoops, and fresh cilantro.',
        calories: 310,
        culturalStory: '宜蘭獨創的街頭神級甜點，將喜宴潤餅皮結合木工刨糖技術與叭噗冰品。香菜的特殊香氣與花生糖酥甜、冰涼冰淇淋形成奇蹟般的平衡，享譽國際。',
        texture: '潤餅皮薄韌柔軟，花生糖粉酥脆香甜，冰淇淋綿密冰涼，香菜增添清新層次。',
        ingredients: ['手工現拉薄潤餅皮', '自製純麥芽花生糖磚', '古早味純手工叭噗冰淇淋', '新鮮現摘翠綠香菜'],
        allergens: ['含花生', '含麩質'],
        cookingMethod: '巨型花生糖磚以特製鋼刨刀手工現削，裹入冰球與香菜現包現吃。',
        bestPairing: '搭配一杯冰鎮冬瓜檸檬或手沖高山烏龍茶。',
        priceRange: 'NT$ 45 - 60',
        tags: ['宜蘭獨創', '現刨花生糖', '香菜冰淇淋', '傳統叭噗']
    },
    {
        foodName: '台南安平古早味白糖粿',
        foodNameEN: 'Tainan Anping Traditional Fried Sugar Dough Fritter',
        foodPrice: 35,
        foodType: ['甜點飲品', '炸物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        foodInfo: '純糯米糰手捏成螺旋長條，投入熱油鍋中炸至外殼微脆膨脹，起鍋迅速滾裹現磨花生粉、香濃芝麻粉或細白砂糖，趁熱咬下一口外脆內軟糯牽絲。',
        foodInfoEN: 'Traditional southern Taiwanese twisted glutinous rice fritter, deep-fried until puffed and rolled in peanut sugar or sesame.',
        calories: 260,
        culturalStory: '台南七夕「做十六歲」成年禮拜七娘媽的傳統祭祀供品。軟糯的白糖粿象徵織女眼淚，如今成為台南各大夜市最具人氣的銅板甜點。',
        texture: '外皮極度薄脆酥口，內心軟糯拉絲如同麻糬，溫熱甜香不黏牙。',
        ingredients: ['純圓糯米水磨糰', '細緻特級白砂糖', '現磨香濃花生粉', '黑芝麻粉'],
        allergens: ['含花生', '含芝麻'],
        cookingMethod: '現捏生糯米糰拉長，入中溫油鍋慢炸膨脹起鍋，熱滾裹粉。',
        bestPairing: '配上一杯現榨金桔檸檬或無糖烏龍茶，甜而不膩。',
        priceRange: 'NT$ 30 - 45',
        tags: ['台南名產', '古法白糖粿', '外脆內拉絲', '銅板甜品']
    },
    {
        foodName: '夜市招牌脆皮草莓糖葫蘆',
        foodNameEN: 'Night Market Crispy Caramel Candied Strawberries',
        foodPrice: 60,
        foodType: ['甜點飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        foodInfo: '嚴選苗栗大湖新鮮紅豔草莓串，沾裹沸騰熬煮的琥珀色金黃焦糖糖漿，自然冷卻形成如水晶玻璃般薄脆透亮的糖衣，一口咬下糖衣碎裂爆出酸甜草莓果汁。',
        foodInfoEN: 'Fresh giant strawberries skewered and coated in a razor-thin, glass-like hard sugar glaze that shatters with sweet tart berry juice.',
        calories: 210,
        culturalStory: '起源於宋朝的宮廷食療果品，傳入台灣後演變成夜市經典散步甜點。除了傳統鳥梨，大湖草莓與小番茄夾蜜餞成為台灣最具特色的當代人氣版。',
        texture: '糖衣如玻璃薄片般清脆爽快，草莓多汁酸甜果肉飽滿。',
        ingredients: ['苗栗大湖當季新鮮紅草莓', '天然二砂糖與純水麥芽糖', '特級天然蜂蜜'],
        allergens: [],
        cookingMethod: '砂糖與麥芽慢火熬至150度拔絲糖漿，生草莓串快速沾裹甩勻冰冷成型。',
        bestPairing: '逛夜市邊走邊吃的甜蜜打卡首選。',
        priceRange: 'NT$ 50 - 70',
        tags: ['大湖草莓', '水晶脆糖衣', '夜市童年回憶', '酸甜多汁']
    },
    {
        foodName: '萬華脆皮爆漿車輪餅 (奶油/紅豆)',
        foodNameEN: 'Crispy Bursting Wheel Cake (Vanilla Custard & Red Bean)',
        foodPrice: 30,
        foodType: ['甜點飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        foodInfo: '圓形特厚銅模高溫烘烤出薄如脆餅的飛碟邊外殼，填入爆滿的屏東萬丹蜜紅豆餡或紐西蘭鮮奶調製之香濃卡士達奶油，一口咬下滾燙濃餡瞬間噴發。',
        foodInfoEN: 'Japanese-inspired Taiwanese wheel cake with wafer-crisp rim, generously stuffed with bursting vanilla cream or sweet adzuki beans.',
        calories: 250,
        culturalStory: '源自日本今川燒，傳入台灣後經過改良發展出獨特的「脆皮飛碟邊」與爆漿極限內餡。如今在台灣夜市更衍生出起司玉米、抹茶麻糬等豐富百搭口味。',
        texture: '邊緣飛碟薄脆如餅乾，蛋糕體鬆軟，內餡爆漿滑順濃稠。',
        ingredients: ['特選低筋粉心麵粉', '屏東萬丹契作蜜紅豆', '紐西蘭天然全脂鮮乳', '天然香草籽與雞蛋'],
        allergens: ['含牛奶/乳製品', '含蛋製品', '含麩質'],
        cookingMethod: '重磅黃銅模具旋轉烙烤粉漿，填入超高內餡合蓋雙面微火烤香。',
        bestPairing: '配一杯冰涼現萃日月潭紅茶或黑糖珍珠奶茶。',
        priceRange: 'NT$ 25 - 40',
        tags: ['飛碟脆邊', '萬丹紅豆', '爆漿奶油', '國民銅板小點']
    },

    // ========================================================
    // 9. 夜市清涼人氣飲品 (Handcrafted Teas & Refreshing Drinks)
    // ========================================================
    {
        foodName: '天然黑糖波霸珍珠鮮奶',
        foodNameEN: 'Tiger Brown Sugar Boba Fresh Milk',
        foodPrice: 65,
        foodType: ['飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1558857563-b37cf5b7a151?auto=format&fit=crop&w=800&q=80',
        foodInfo: '純手工以台灣柴燒黑糖慢火蜜煮大顆木薯粉圓一小時，沿透明杯壁旋轉淋出琥珀色虎紋黑糖漿，倒入100%小農純濃鮮乳，不加一滴水，冷熱交織香濃絕頂。',
        foodInfoEN: 'Chewy tapioca pearls slow-simmered in rich dark brown sugar syrup, coated along the cup walls and filled with 100% cold farm milk.',
        calories: 440,
        culturalStory: '台灣掀起全球黑糖珍珠狂潮的代表作！溫熱軟Q的現煮黑糖粉圓撞上冰冷香純鮮奶，冷熱交融與虎紋視覺效果，讓台灣手搖飲再度征服全世界。',
        texture: '黑糖珍珠溫熱軟Q富嚼勁，鮮奶純濃滑順，黑糖香氣濃烈深沉。',
        ingredients: ['柴燒純黑糖', '台灣特級木薯大粉圓 (波霸)', '台灣在地小農單一牧場純鮮乳'],
        allergens: ['含牛奶/乳製品'],
        cookingMethod: '黑糖炒出焦香後慢火熬煮粉圓45分鐘燜透，杯緣塗漿倒入冰鮮奶。',
        bestPairing: '飲用前上下搖晃十五下，配上一份鹹酥雞或雞排堪稱世界最邪惡組合。',
        priceRange: 'NT$ 60 - 80',
        tags: ['台灣之光', '虎紋黑糖', '小農鮮乳', '風靡全球']
    },
    {
        foodName: '阿里山野生愛玉檸檬凍飲',
        foodNameEN: 'Alishan Wild Aiyu Jelly Lemon Iced Drink',
        foodPrice: 50,
        foodType: ['飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        foodInfo: '嚴選阿里山海拔千米野生愛玉子，以富含礦物質天然泉水純手工搓洗凝結出剔透如水晶的天然愛玉凍，搭配屏東九如現壓新鮮綠檸檬汁與二砂糖蜜，晶亮沁涼。',
        foodInfoEN: 'Hand-rubbed natural Alishan mountain aiyu fig jelly swimming in fresh-squeezed tart lemon juice and golden cane sugar syrup.',
        calories: 140,
        culturalStory: '愛玉子是全球僅台灣特有的桑科榕屬植物，由特有種愛玉小蜂授粉。天然搓洗的愛玉凍富含果膠熱量極低，是台灣夏季最天然健康的清涼解暑聖品。',
        texture: '愛玉凍滑嫩如果凍吸入口中即化，檸檬汁酸甜爽口生津止渴。',
        ingredients: ['阿里山野生高山愛玉子', '屏東九如鮮榨綠檸檬汁', '古法純蔗糖水', '純天然礦泉水'],
        allergens: [],
        cookingMethod: '愛玉籽裝棉袋於硬水中手搓出果膠靜置凝固，調入鮮檸檬糖水與碎冰。',
        bestPairing: '吃完烤肉串、炸雞排或麻辣鴨血後的解膩必備神器。',
        priceRange: 'NT$ 45 - 65',
        tags: ['台灣特有種', '野生愛玉', '手搓果膠', '低卡消暑']
    },
    {
        foodName: '白玉苦瓜現榨蜂蜜檸檬汁',
        foodNameEN: 'Fresh White Bitter Gourd Honey Lemon Cooler',
        foodPrice: 65,
        foodType: ['飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        foodInfo: '全台夜市水果攤的降火絕活！精選外觀晶瑩如白玉的台灣特產白玉苦瓜，去籽去膜後新鮮現榨，搭配天然純龍眼蜂蜜與鮮檸檬汁，入口甘甜微甘不苦，清涼退火。',
        foodInfoEN: 'Crisp white jade bitter melon cold-pressed with pure longan honey and lemon, refreshing with a delicate sweet aftertaste without bitterness.',
        calories: 120,
        culturalStory: '台灣農業改良的奇蹟品種「白玉苦瓜」，水分飽滿、苦味極淡甚至帶甜味。夜市現打苦瓜汁標榜「降火排毒解燥」，是各國觀光客驚豔的台灣特色蔬果飲。',
        texture: '冰涼爽口汁液清澈，蜂蜜甘甜與檸檬清酸完美掩蓋微弱苦味，尾韻回甘。',
        ingredients: ['台灣特選白玉苦瓜', '天然純龍眼蜂蜜', '現榨屏東檸檬汁', '純淨過濾碎冰'],
        allergens: [],
        cookingMethod: '苦瓜去白膜切條，高速慢磨壓榨出原汁，雪克搖出細緻泡沫。',
        bestPairing: '吃完重口味油炸或炭烤後的最佳健康降火排毒解膩飲品。',
        priceRange: 'NT$ 60 - 80',
        tags: ['白玉苦瓜', '降火排毒', '龍眼蜂蜜', '清爽回甘']
    }
];

module.exports = {
    GRAND_TAIWAN_FOODS
};
