/**
 * 全台灣代表性觀光夜市完整大數據庫
 * 涵蓋北部、中部、南部、東部與離島 29 座必訪夜市
 */
const ALL_TAIWAN_NIGHT_MARKETS = [
    // ==========================================
    // 北部地區 (Northern Taiwan)
    // ==========================================
    {
        name: '士林觀光夜市',
        nameen: 'Shilin Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台北市士林區大東路、基河路周邊',
        city: '台北市',
        cityEn: 'Taipei',
        region: 'north',
        positionGuidelines: '搭乘台北捷運淡水信義線至「劍潭站」1號出口，步行約3分鐘即可抵達。',
        brief: '台北市規模最大且名聞遐邇的國際觀光夜市，集合各式經典小吃、服飾配件與遊樂攤位。',
        introduction: '士林夜市歷史可追溯至清末光緒年間，範圍涵蓋基河路、大東路、大南路與文林路一帶。擁有比臉大炸雞排、辛發亭雪花冰、老士林大香腸、生煎包等經典名產，是國內外觀光客來台指名必訪的第一站。',
        openDays: '每日 16:00 - 00:00',
        rating: 4.8,
        lat: 25.088,
        lng: 121.524
    },
    {
        name: '饒河街觀光夜市',
        nameen: 'Raohe Street Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台北市松山區饒河街',
        city: '台北市',
        cityEn: 'Taipei',
        region: 'north',
        positionGuidelines: '搭乘捷運松山新店線至「松山站」1號或2號出口，出站即可見慈祐宮牌樓。',
        brief: '慈祐宮旁熱鬧非凡的傳統長街型夜市，以米其林必比登推薦胡椒餅與藥燉排骨聞名。',
        introduction: '饒河街夜市全長約600公尺，入口處有氣派的金碧輝煌牌坊與三百年歷史的松山慈祐宮。街內美食匯聚，以窯烤出爐即爆汁的福州世祖胡椒餅、陳董藥燉排骨、東發號蚵仔麵線、下港名彭臭豆腐最為知名。',
        openDays: '每日 17:00 - 23:30',
        rating: 4.8,
        lat: 25.051,
        lng: 121.577
    },
    {
        name: '寧夏夜市',
        nameen: 'Ningxia Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台北市大同區寧夏路 (民生西路至南京西路段)',
        city: '台北市',
        cityEn: 'Taipei',
        region: 'north',
        positionGuidelines: '捷運淡水信義線「雙連站」1號出口步行約8分鐘；或「中山站」步行約10分鐘。',
        brief: '千歲宴創始地！台北老字號台灣古早味美食聖地，環保無煙夜市示範標竿。',
        introduction: '寧夏夜市被老台北人譽為「最道地的古早味廚房」。聚集圓環邊蚵仔煎、劉芋仔蛋黃芋餅、豬肝榮仔、環記麻油雞等眾多米其林必比登推薦排隊名店，堅持傳統手藝，小吃密度全台最高。',
        openDays: '每日 17:00 - 01:00',
        rating: 4.9,
        lat: 25.055,
        lng: 121.515
    },
    {
        name: '南機場夜市',
        nameen: 'Nanjichang Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台北市中正區中華路二段307巷至315巷',
        city: '台北市',
        cityEn: 'Taipei',
        region: 'north',
        positionGuidelines: '捷運「小南門站」或「西門站」轉乘公車至「南機場公寓站」步行約3分鐘。',
        brief: '饕客公認「全台北CP值最高、無雷美食密度之冠」的在地人私房夜市。',
        introduction: '日治時期曾為練兵場與軍用機場而得名。夜市規模精緻，卻藏有極多實力派名攤：山內雞肉、臭老闆現蒸臭豆腐、阿男麻油雞、秀昌水餃、鈺師傅上海生煎包，幾乎每攤都是米其林入選或排隊傳奇。',
        openDays: '每日 17:00 - 00:00',
        rating: 4.8,
        lat: 25.030,
        lng: 121.505
    },
    {
        name: '師大夜市',
        nameen: 'Shida Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台北市大安區師大路與龍泉街周邊',
        city: '台北市',
        cityEn: 'Taipei',
        region: 'north',
        positionGuidelines: '捷運松山新店線至「台電大樓站」3號出口，沿師大路步行約5分鐘。',
        brief: '鄰近國立臺灣師範大學，充滿學生青春活力與異國人文氣息的複合商圈夜市。',
        introduction: '緊鄰大學校園，融合台灣傳統夜市與歐美異國風情。名店如燈籠加熱滷味、師園鹽酥雞、好事花生冰火菠蘿油、許記生煎包，以及眾多文青咖啡館與流行服飾小店，深受年輕學子與文青喜愛。',
        openDays: '每日 16:30 - 23:00',
        rating: 4.7,
        lat: 25.025,
        lng: 121.529
    },
    {
        name: '臨江街觀光夜市 (通化夜市)',
        nameen: 'Linjiang Street Night Market (Tonghua)',
        marketIcon: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台北市大安區臨江街 (通化街至基隆路段)',
        city: '台北市',
        cityEn: 'Taipei',
        region: 'north',
        positionGuidelines: '捷運淡水信義線「信義安和站」3號或4號出口，沿通化街步行約5分鐘。',
        brief: '信義商圈旁的米其林美食一條街，冰火湯圓與經典鹽水雞名揚全台。',
        introduction: '距離台北101與信義商圈僅一步之遙，白天是傳統菜市場，夜晚變身美食一條街。御品元冰火湯圓、紅花麻辣鹽水雞、梁記滷味、駱記小炒皆榮獲米其林必比登推介，宵夜聚餐首選。',
        openDays: '每日 18:00 - 00:00',
        rating: 4.8,
        lat: 25.031,
        lng: 121.554
    },
    {
        name: '樂華夜市',
        nameen: 'Lehua Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
        marketLocation: '新北市永和區永平路 (永和路至中山路段)',
        city: '新北市',
        cityEn: 'New Taipei',
        region: 'north',
        positionGuidelines: '搭乘台北捷運中和新蘆線至「頂溪站」1號出口，步行約8分鐘。',
        brief: '新北市永和最具代表性夜市，美食攤位整齊劃一、老字號經典雲集。',
        introduction: '創立超過半世紀的在地大夜市，以永美雪花冰、樂華蚵仔煎、阿爸の芋圓蔗片冰、肥豬的攤紅槽鹽酥雞、天下佈武日月潭紅茶等名聞遐邇，道路寬敞好逛，是在地雙和人的深夜廚房。',
        openDays: '每日 17:00 - 00:00',
        rating: 4.8,
        lat: 25.009,
        lng: 121.512
    },
    {
        name: '三和夜市',
        nameen: 'Sanhe Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=800&q=80',
        marketLocation: '新北市三重區中央北路 (文化北路至自強路段)',
        city: '新北市',
        cityEn: 'New Taipei',
        region: 'north',
        positionGuidelines: '捷運中和新蘆線「台北橋站」出口步行約3分鐘即可進入中央北路夜市街。',
        brief: '新北三重最具歷史的長型夜市，傳承超過一甲子的真材實料庶民美味。',
        introduction: '白天為傳統中央市場，晚上則是綿延近一公里的繁華夜市。招牌名吃包含傳承三代的萬粒肉圓、朱記花枝羹、市場口木瓜牛奶、小楊脆腸與香脆地瓜球，價格親民且料好實在。',
        openDays: '每日 17:30 - 00:00',
        rating: 4.7,
        lat: 25.064,
        lng: 121.498
    },
    {
        name: '基隆廟口夜市',
        nameen: 'Keelung Miaokou Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
        marketLocation: '基隆市仁愛區仁三路 (奠濟宮周邊)',
        city: '基隆市',
        cityEn: 'Keelung',
        region: 'north',
        positionGuidelines: '搭乘台鐵至「基隆火車站」南站出口，步行約8-10分鐘即可抵達。',
        brief: '全台唯一的黃色燈籠百年海港夜市，鼎邊趖、泡泡冰與天婦羅的發源地。',
        introduction: '以奠濟宮為中心發展，規劃整齊統一掛上鵝黃色傳統燈籠，全天候香味撲鼻。必吃名攤包含：邢記鼎邊趖、營養三明治、一口吃香腸、王記天婦羅、沈記泡泡冰與油蔥碳烤三明治，全台無可取代的港都風味。',
        openDays: '每日 12:00 - 00:00 (夜間最為熱鬧)',
        rating: 4.8,
        lat: 25.128,
        lng: 121.743
    },
    {
        name: '中原夜市',
        nameen: 'Chung Yuan Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80',
        marketLocation: '桃園市中壢區日新路、實踐路 (中原大學周邊)',
        city: '桃園市',
        cityEn: 'Taoyuan',
        region: 'north',
        positionGuidelines: '搭乘台鐵至「中壢火車站」，轉乘中壢客運公車約10分鐘至中原大學站。',
        brief: '大學校園旁超高CP值美食熱區，銅板甜點與創意料理的誕生地。',
        introduction: '緊鄰中原大學，以價格平實、份量驚人著稱。著名的開運屋QQ地瓜球、皇后先生手搖飲、御冠園鮮肉湯包、家鄉碳烤雞排、長髮叔叔蔥油餅吸引眾多外縣市遊客特地朝聖。',
        openDays: '每日 16:30 - 00:30',
        rating: 4.7,
        lat: 24.957,
        lng: 121.240
    },
    {
        name: '新竹城隍廟夜市',
        nameen: 'Hsinchu City God Temple Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80',
        marketLocation: '新竹市北區中山路75號 (城隍廟埕與周邊商圈)',
        city: '新竹市',
        cityEn: 'Hsinchu',
        region: 'north',
        positionGuidelines: '搭乘台鐵至「新竹火車站」，沿中正路接東門圓環步行約10分鐘。',
        brief: '三級古蹟城隍廟口古早味小吃集中地，新竹貢丸、米粉與肉圓的朝聖聖殿。',
        introduction: '已有兩百多年歷史，廟埕與周邊巷弄密密麻麻佈滿老字號。阿城號米粉炒、西大發城隍包、阿忠肉圓、柳家肉燥飯與潤餅是遠近馳名的新竹三寶代表，是造訪風城必訪的歷史美食地標。',
        openDays: '每日 09:00 - 22:30',
        rating: 4.7,
        lat: 24.804,
        lng: 120.965
    },

    // ==========================================
    // 中部地區 (Central Taiwan)
    // ==========================================
    {
        name: '逢甲夜市',
        nameen: 'Fengjia Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台中市西屯區文華路、福星路周邊',
        city: '台中市',
        cityEn: 'Taichung',
        region: 'central',
        positionGuidelines: '台中高鐵站或火車站搭乘公車(33、35、25路)至「逢甲大學(福星路)」站。',
        brief: '全台灣規模最大、創新小吃研發基地的觀光夜市霸主！',
        introduction: '全台創意夜市小吃的發源重鎮！大腸包小腸、明倫蛋餅、一心素食臭豆腐、海邊小屋乾燒蛤蜊、溫家地瓜球皆是排隊傳奇。潮流服飾、電子3C與美食應有盡有，年營業額與造訪人次冠絕全台。',
        openDays: '每日 16:00 - 01:00',
        rating: 4.8,
        lat: 24.179,
        lng: 120.648
    },
    {
        name: '一中街夜市',
        nameen: 'Yizhong Street Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1558857563-b37cf5b7a151?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台中市北區一中街 (台中科技大學對面)',
        city: '台中市',
        cityEn: 'Taichung',
        region: 'central',
        positionGuidelines: '自台中火車站搭乘公車約10分鐘至「台中科技大學」或「中友百貨」站。',
        brief: '台中學生與年輕人朝聖核心，豐仁冰、特大雞排與潮流服飾集散地。',
        introduction: '圍繞台中一中與台中科技大學形成，擁有極高活力與平價消費特色。一中豪大雞排、豐仁冰、打餅舖烙餅、上和園滷味、21臭豆腐每天大排長龍，集結最新潮的美食與街頭流行。',
        openDays: '每日 11:00 - 23:00',
        rating: 4.7,
        lat: 24.148,
        lng: 120.685
    },
    {
        name: '旱溪夜市',
        nameen: 'Hanxi Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台中市東區旱溪東路一段與振興路口',
        city: '台中市',
        cityEn: 'Taichung',
        region: 'central',
        positionGuidelines: '自台中火車站轉乘計程車約8分鐘，或搭乘市區公車至「東門橋站」。',
        brief: '台中在地人最愛的傳統流動空地夜市，規劃整齊、平價美味大集合。',
        introduction: '佔地超過六千坪的大型空地夜市，劃分清晰且動線寬敞。方臉師傅蒜香豆干、波蘭手工保羅蛋糕、惡魔雞排、酥炸大魷魚、正豐原祖傳鳳梨冰吸引滿滿人潮，被評為台中最有人情味夜市。',
        openDays: '每週二、四、五、六 17:00 - 01:00',
        rating: 4.8,
        lat: 24.135,
        lng: 120.702
    },
    {
        name: '精誠夜市 (高貴林夜市)',
        nameen: 'Jingcheng Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
        marketLocation: '彰化縣彰化市精誠路與林森路路口',
        city: '彰化縣',
        cityEn: 'Changhua',
        region: 'central',
        positionGuidelines: '自彰化火車站轉乘計程車約7分鐘，或沿三民路接林森路車程約5分鐘。',
        brief: '彰化規模最大、在地知名度最高的熱門夜市，松林炭烤與碳烤雞排齊聚。',
        introduction: '彰化市週三至週日最具代表性的空地大夜市，攤位多達數百攤。松林烤肉、酥皮生煎包、數十家老牌地瓜球、章魚小丸子與碳烤雞排香氣四溢，是體驗道地中台灣夜市文化的絕佳去處。',
        openDays: '每週三、四、五、六、日 17:30 - 23:30',
        rating: 4.7,
        lat: 24.068,
        lng: 120.528
    },
    {
        name: '草鞋墩人文觀光夜市',
        nameen: 'Caoxiedun Tourism Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=800&q=80',
        marketLocation: '南投縣草屯鎮中正路1039號 (寶島時代村旁)',
        city: '南投縣',
        cityEn: 'Nantou',
        region: 'central',
        positionGuidelines: '國道三號中興交流道下往草屯方向，沿中正路行駛約5分鐘即可到達。',
        brief: '南投縣規模第一的觀光夜市，傳統懷舊紅燈籠與中台灣熱炒美食聚集。',
        introduction: '結合人文復古與地方特色的超大型觀光夜市。各種香烤大雞排、鹿港現煮蚵仔煎、手工純糖古早味粉圓以及多元兒童遊樂攤位，每逢週末湧入大量南投與台中遊客。',
        openDays: '每週五、六、日 18:00 - 23:30',
        rating: 4.6,
        lat: 23.987,
        lng: 120.686
    },
    {
        name: '斗六人文夜市',
        nameen: 'Douliu Tourism Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
        marketLocation: '雲林縣斗六市明德北路三段與公理路口',
        city: '雲林縣',
        cityEn: 'Yunlin',
        region: 'central',
        positionGuidelines: '自斗六火車站轉乘計程車約5分鐘，或由雲林科技大學步行約12分鐘。',
        brief: '雲林縣佔地最廣、攤位最多的巨型流動夜市，雲林在地人週末聚會首選。',
        introduction: '佔地數千坪的巨無霸夜市，聚集近五百個攤位。何佳佳蔥油餅、炸彈蔥油餅、豆乳雞翅、雅淳水果茶現煮鳳梨冰與現烤深海大魷魚等排隊名攤林立，物美價廉深具地方鄉土情懷。',
        openDays: '每週二、六 17:30 - 00:00',
        rating: 4.7,
        lat: 23.708,
        lng: 120.534
    },

    // ==========================================
    // 南部地區 (Southern Taiwan)
    // ==========================================
    {
        name: '花園夜市',
        nameen: 'Tainan Garden Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台南市北區海安路三段與和緯路三段口',
        city: '台南市',
        cityEn: 'Tainan',
        region: 'south',
        positionGuidelines: '自台南火車站搭乘0左路公車或計程車約10分鐘至海安路三段花園夜市站。',
        brief: '「大大武花大武花」南台灣夜市之王！旗海飄揚的千攤美食奇觀。',
        introduction: '南台灣知名度最高的超人氣流動夜市，滿天飄揚的高聳招牌旗幟是其經典標誌。必吃名攤包含二師兄古味三杯滷味、陳記麻辣鴨血、統大碳烤香雞排、阿美芭樂與延記地瓜球，每週限定三日營業依然人潮爆滿。',
        openDays: '每週四、六、日 17:00 - 00:00',
        rating: 4.8,
        lat: 23.011,
        lng: 120.198
    },
    {
        name: '大東夜市',
        nameen: 'Dadong Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台南市東區林森路一段 (台南市監理站旁)',
        city: '台南市',
        cityEn: 'Tainan',
        region: 'south',
        positionGuidelines: '台南火車站後站搭乘計程車約6分鐘，或騎乘YouBike至林森路一段站。',
        brief: '台南市東區最受年輕族群喜愛的熱門夜市，美食攤位密度高且經典雲集。',
        introduction: '位於台南市區核心，交通便利。紅妃香腸炒大腸包小腸、小叮噹牛排、古早味拔絲地瓜、原住民烤肉與台南鮮切水果應有盡有，是台南人口訣「大大武花大武花」週一二五的必逛重鎮。',
        openDays: '每週一、二、五 17:30 - 00:00',
        rating: 4.8,
        lat: 22.986,
        lng: 120.222
    },
    {
        name: '武聖夜市',
        nameen: 'Wusheng Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台南市中西區武聖路69巷42號',
        city: '台南市',
        cityEn: 'Tainan',
        region: 'south',
        positionGuidelines: '自台南火車站搭乘計程車約8分鐘，或沿成功路接武聖路。',
        brief: '創立於1984年，台南歷史最悠久的代表性夜市，在地老饕的私藏美味。',
        introduction: '歷史長達40餘年，被許多台南在地人評為逛起來最舒適、重複性最低的夜市。阿三哥蚵仔煎、大腸包小腸、老牌烤玉米、古早味現榨楊桃湯以及射氣球遊樂區，充滿濃厚的童年與懷舊情懷。',
        openDays: '每週三、五、六 17:30 - 00:30',
        rating: 4.7,
        lat: 23.003,
        lng: 120.188
    },
    {
        name: '六合國際觀光夜市',
        nameen: 'Liuhe Tourist Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
        marketLocation: '高雄市新興區六合二路 (自立二路至中山一路段)',
        city: '高雄市',
        cityEn: 'Kaohsiung',
        region: 'south',
        positionGuidelines: '搭乘高雄捷運紅線或橘線至「美麗島站」11號出口，出站即達夜市入口。',
        brief: '高雄國際能見度最高的大道型觀光夜市，海產粥與木瓜牛奶揚名海外。',
        introduction: '街道平整寬敞、燈火通明，曾榮獲全台最友善夜市殊榮。鄭老牌木瓜牛奶、莊記海產粥、方記水餃、烤肉之家與東山鴨頭享譽全亞洲，多語標示與便利的捷運換乘深受國際旅客喜愛。',
        openDays: '每日 17:30 - 02:00',
        rating: 4.7,
        lat: 22.631,
        lng: 120.301
    },
    {
        name: '瑞豐夜市',
        nameen: 'Ruifeng Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
        marketLocation: '高雄市鼓山區裕誠路與南屏路路口 (漢神巨蛋商圈旁)',
        city: '高雄市',
        cityEn: 'Kaohsiung',
        region: 'south',
        positionGuidelines: '搭乘高雄捷運紅線至「巨蛋站」1號出口，沿裕誠路步行約5分鐘。',
        brief: '高雄年輕人與大學生人氣第一夜市！近千攤位格狀排列、創新美食雲集。',
        introduction: '高雄在地年輕族群的最愛，攤位緊密相鄰、熱氣騰騰。天使厚切雞排、萬國牛排、曾氏福建炒麵、爆漿拔絲蔥抓餅、蒙古烤肉與泰式奶茶每天湧入擠得水洩不通的朝聖人潮。',
        openDays: '每週二、四、五、六、日 17:30 - 00:30',
        rating: 4.8,
        lat: 22.666,
        lng: 120.300
    },
    {
        name: '嘉義文化路夜市',
        nameen: 'Chiayi Wenhua Road Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
        marketLocation: '嘉義市東區文化路 (中山路噴水圓環至垂楊路段)',
        city: '嘉義市',
        cityEn: 'Chiayi',
        region: 'south',
        positionGuidelines: '搭乘台鐵至「嘉義火車站」，出站後沿中山路步行約10分鐘至中央噴水圓環。',
        brief: '世界級美食紀錄片取材地！沙鍋魚頭、火雞肉飯與豆漿豆花的美食朝聖大道。',
        introduction: '全長約500公尺，劃分行人徒步區。名列Netflix紀錄片的世界級名店林聰明沙鍋魚頭、源興御香屋葡萄柚綠茶、郭家火雞肉飯、阿娥豆漿豆花是來嘉義絕不能錯過的必吃極品。',
        openDays: '每日 17:30 - 00:00',
        rating: 4.8,
        lat: 23.479,
        lng: 120.449
    },
    {
        name: '墾丁大街夜市',
        nameen: 'Kenting Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1509315811345-672d83ef2fbc?auto=format&fit=crop&w=800&q=80',
        marketLocation: '屏東縣恆春鎮墾丁路',
        city: '屏東縣',
        cityEn: 'Pingtung',
        region: 'south',
        positionGuidelines: '搭乘台灣好行「墾丁快線」或客運至「墾丁大街站」下車即可。',
        brief: '全台灣最南端的南洋度假風夜市，炭烤海鮮、熱帶調酒與異國海灘風情。',
        introduction: '綿延一公里的墾丁大街夜晚熱鬧非凡。沿街充滿炭烤大生蠔、原住民烤山豬肉、香酥花枝丸、一品滷味以及充滿南洋風情的露天調酒吧與海島特色服飾，熱力四射的南國度假氛圍無可取代。',
        openDays: '每日 17:30 - 23:30',
        rating: 4.7,
        lat: 21.944,
        lng: 120.797
    },

    // ==========================================
    // 東部地區及離島 (Eastern Taiwan & Islands)
    // ==========================================
    {
        name: '羅東觀光夜市',
        nameen: 'Luodong Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80',
        marketLocation: '宜蘭縣羅東鎮公園路、民生路 (羅東中山公園周圍)',
        city: '宜蘭縣',
        cityEn: 'Yilan',
        region: 'east',
        positionGuidelines: '搭乘台鐵至「羅東火車站」前站出口，沿公正路接興東路步行約8分鐘。',
        brief: '東台灣最具規模與知名度之超級夜市，宜蘭三星蔥派與當歸羊肉湯發源地。',
        introduction: '環繞羅東中山公園而建，呈口字型動線。阿灶伯當歸羊肉湯、義豐蔥油派、魏姐包心粉圓、小春糕渣卜肉與烤肉風味名揚全台，是國人前往宜蘭旅遊必排入的第一名夜間行程。',
        openDays: '每日 17:00 - 00:00',
        rating: 4.8,
        lat: 24.677,
        lng: 121.770
    },
    {
        name: '宜蘭東門觀光夜市',
        nameen: 'Yilan Dongmen Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=800&q=80',
        marketLocation: '宜蘭縣宜蘭市東港路口 (宜蘭東港陸橋下)',
        city: '宜蘭縣',
        cityEn: 'Yilan',
        region: 'east',
        positionGuidelines: '搭乘台鐵至「宜蘭火車站」前站出口，出站右轉步行約5分鐘即達陸橋下。',
        brief: '高架橋下遮風避雨的在地人私房夜市，彭記蔥油餅與嘟好燒飄香數十年。',
        introduction: '利用東港陸橋下方空間規劃而成，即使下雨天也能自在逛街。以傳統點心「嘟好燒」、彭記蔥油餅、天橋下臭豆腐、梁大胖碳烤以及老牌搖搖冰聞名，充滿濃厚的宜蘭在地人情味。',
        openDays: '每日 17:00 - 00:00',
        rating: 4.7,
        lat: 24.757,
        lng: 121.758
    },
    {
        name: '花蓮東大門國際觀光夜市',
        nameen: 'Hualien Dongdamen Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
        marketLocation: '花蓮縣花蓮市中山路50號',
        city: '花蓮縣',
        cityEn: 'Hualien',
        region: 'east',
        positionGuidelines: '自花蓮火車站搭乘花蓮客運或市區公車約10分鐘至「東大門夜市站」即可抵達。',
        brief: '東台灣佔地最遼闊之國際級夜市，結合原住民風味一條街與陽光步道。',
        introduction: '佔地九公頃的大型國際觀光夜市，鋪設典雅花崗岩步道。劃分「福町夜市」、「原住民一條街」、「自強夜市」與「大陸各省一條街」四大主題區。第一家烤肉串、林記燒玉米、強蛋餅、蔣家官財板吸引各國旅人慕名而來。',
        openDays: '每日 18:00 - 00:00',
        rating: 4.8,
        lat: 23.974,
        lng: 121.613
    },
    {
        name: '台東觀光夜市',
        nameen: 'Taitung Tourist Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=800&q=80',
        marketLocation: '台東縣台東市正氣路 (博愛路至中山路段)',
        city: '台東縣',
        cityEn: 'Taitung',
        region: 'east',
        positionGuidelines: '位於台東市區正氣路，距台東轉運站步行約5分鐘。',
        brief: '台東水果街入夜後的美味變身，正東山鴨頭與派大星生蠔人潮滿滿。',
        introduction: '白天是著名的正氣路水果街，週四至週六夜晚則封街成為行人徒步美食天堂。東山鴨頭、老牌水煎包、烤生蠔、烤肉刈包與台東在地洛神花茶風味獨具，散發熱情純樸的後山慢活氣息。',
        openDays: '每週四、五、六 17:00 - 23:00',
        rating: 4.7,
        lat: 22.754,
        lng: 121.150
    },
    {
        name: '馬公中正路商圈夜市',
        nameen: 'Penghu Magong Zhongzheng Night Market',
        marketIcon: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
        marketLocation: '澎湖縣馬公市中正路 (臨近馬公港)',
        city: '澎湖縣',
        cityEn: 'Penghu',
        region: 'east',
        positionGuidelines: '自馬公港客運碼頭步行約3分鐘即可抵達中正路商圈。',
        brief: '澎湖菊島夏日最熱鬧的港灣夜市，仙草冰、炸黑糖糕與海鮮小管麵線。',
        introduction: '緊鄰馬公港與花火節觀音亭園區，是離島澎湖夏日最核心的夜間商圈。玉冠嫩仙草、澎湖小管麵線、香酥炸黑糖糕、現烤帶殼牡蠣與仙人掌冰淇淋，海風輕拂中享受極致海島鮮味。',
        openDays: '每日 17:00 - 23:00 (夏秋花火節旺季最熱鬧)',
        rating: 4.7,
        lat: 23.567,
        lng: 119.566
    }
];

module.exports = {
    ALL_TAIWAN_NIGHT_MARKETS
};
