/**
 * 台灣夜市大百科（第二輯）：更多全台各縣市道地街頭神級美食 (Grand Taiwan Food Part 2)
 */

const ADDITIONAL_TAIWAN_FOODS = [
    // 經典飯食與主食小吃
    {
        foodName: '古早味豬油拌飯',
        foodNameEN: 'Old-School Lard & Shallot Rice with Raw Egg Yolk',
        foodPrice: 40,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '熱騰騰白飯淋上自炸溫體黑豬油與古法純釀黑豆油膏，打上一顆新鮮土雞蛋生蛋黃與油蔥酥，拌勻後米粒金黃油亮，香氣直擊靈魂。',
        foodInfoEN: 'Hot steamed rice drizzled with fragrant pork lard, sweet soy sauce, fried shallots, and topped with a creamy raw farm egg yolk.',
        calories: 410,
        culturalStory: '物資匱乏年代台灣農村最質樸卻最奢華的美味，一匙豬油與醬油拌飯養活數代台灣人。如今在各大復古夜市重現，成為年輕人爭相朝聖的懷舊名品。',
        texture: '米粒被豬油與蛋黃均勻包裹，滑潤細膩，油蔥酥香脆酥口。',
        ingredients: ['自炸純黑豬油', '西螺陳年黑豆蔭油膏', '產銷履歷生食級土雞蛋', '手切紅蔥酥', '台梗九號米'],
        allergens: ['含蛋製品', '含大豆'],
        cookingMethod: '現盛滾燙米飯，趁熱淋上熱豬油與油膏，打上生蛋黃。',
        bestPairing: '搭配一碗古早味蛤蜊大骨湯，回味童年最純粹的溫暖。',
        priceRange: 'NT$ 35 - 50',
        tags: ['懷舊古早味', '生蛋黃瀑布', '香濃豬油', '靈魂拌飯']
    },
    {
        foodName: '東港鮮味旗魚肉燥飯',
        foodNameEN: 'Donggang Sailfish Minced Fish Floss Rice',
        foodPrice: 45,
        foodType: ['傳統小吃', '海鮮鍋物'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '屏東東港漁港新鮮旗魚肉細切，與冰糖、紅蔥頭與醬油慢火煸炒，魚肉鬆而不乾澀，帶有天然海魚甘甜，清爽不油膩。',
        foodInfoEN: 'Fresh sailfish finely ground and slow-simmered with shallots and soy glaze, light, savory, and rich in marine umami.',
        calories: 360,
        culturalStory: '南部漁港特有的主食小吃，結合了海魚的鮮甜與肉燥的甘醇，蛋白質豐富且脂肪較低，是屏東與高雄夜市的在地私房美食。',
        texture: '魚肉鬆軟甘甜，米飯顆粒分明，醬汁甘醇微甜。',
        ingredients: ['東港現撈旗魚肉', '自製紅蔥頭', '純釀古法黑豆醬油', '冰糖與五香粉'],
        allergens: ['含魚類', '含大豆'],
        cookingMethod: '旗魚肉汆燙去腥手撕細碎，與蔥油及醬汁小火炒至乾香入味。',
        bestPairing: '搭配鮮魚蛤蜊薑絲湯或炸天婦羅，風味絕倫。',
        priceRange: 'NT$ 40 - 55',
        tags: ['東港海味', '旗魚肉燥', '清爽低脂', '漁港特色']
    },
    {
        foodName: '宜蘭正宗櫻桃鴨肉飯',
        foodNameEN: 'Yilan Cherry Valley Duck Rice',
        foodPrice: 75,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '嚴選宜蘭三星鄉好山好水培育之櫻桃谷品種肉鴨，慢火蒸烤至皮脆肉嫩，切片鋪在飯上，淋上香濃純鴨油與甘甜肉汁，油香四溢。',
        foodInfoEN: 'Tender slices of premium Yilan Cherry Valley duck served over rice drizzled with rich rendered duck fat and sweet glaze.',
        calories: 490,
        culturalStory: '宜蘭櫻桃鴨享譽全台，油脂豐厚肉質細嫩。除了國宴烤鴨，夜市平價櫻桃鴨肉飯讓饕客以銅板價就能品嚐極品鴨油與嫩肉。',
        texture: '鴨肉細緻帶彈性，鴨皮油潤甘香，鴨油白飯香濃無比。',
        ingredients: ['宜蘭三星櫻桃谷肉鴨', '自熬純鴨油', '古法油蔥酥', '西螺米', '特調甘醇鴨汁'],
        allergens: ['含大豆', '含小麥'],
        cookingMethod: '全鴨低溫慢烤鎖汁，手切薄片，澆淋沸騰鴨油與甘醇高湯。',
        bestPairing: '搭配當歸鴨肉湯或冬瓜蛤蜊湯，香氣層次更豐富。',
        priceRange: 'NT$ 65 - 90',
        tags: ['宜蘭櫻桃鴨', '極品鴨油', '肉嫩多汁', '平民國宴']
    },

    // 經典特色小吃與點心
    {
        foodName: '彰化王功酥脆生蚵高麗菜嗲',
        foodNameEN: 'Changhua Wanggong Crispy Oyster & Cabbage Cake (O-De)',
        foodPrice: 50,
        foodType: ['炸物', '傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
        foodInfo: '特製圓鐵杓抹上黃豆粉漿，鋪上厚厚一層鮮脆高麗菜絲、韭菜、新鮮肥美生蚵與溫體豬絞肉，再蓋上粉漿投入高溫油鍋，炸至外殼極度金黃酥脆。',
        foodInfoEN: 'Iron ladle filled with fresh oysters, minced pork, cabbage, and leek dipped in soybean batter, deep-fried ultra-crisp.',
        calories: 380,
        culturalStory: '彰化王功漁港傳承百年的沿海特色小吃，以現剖潮間帶珍珠蚵為餡，皮薄酥脆，蔬菜與蚵仔在高溫油炸中鎖住鮮甜水分。',
        texture: '外皮如同餅乾般香脆，內餡高麗菜脆甜多汁，生蚵爆漿鮮甜。',
        ingredients: ['王功產地直採鮮蚵', '新鮮高麗菜與韭菜碎', '黃豆與在來米調配粉漿', '溫體豬絞肉', '甜辣海山醬'],
        allergens: ['含貝類蚵仔', '含大豆'],
        cookingMethod: '鐵杓堆疊滿餡沾粉漿，入油鍋大火炸透脫模，炸至金黃金赤。',
        bestPairing: '沾特調蒜蓉甜辣醬，配一碗赤肉羹湯最過癮。',
        priceRange: 'NT$ 45 - 60',
        tags: ['王功名產', '蚵嗲爆汁', '薄脆餅皮', '百年漁港手藝']
    },
    {
        foodName: '花蓮復興街爆漿炸蛋蔥油餅',
        foodNameEN: 'Hualien Bursting Runny-Egg Scallion Pancake',
        foodPrice: 45,
        foodType: ['炸物', '傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        foodInfo: '高溫熱油鍋內手工現桿麵皮瞬間膨脹如氣球般金黃酥脆！隨即打入一顆新鮮雞蛋，十秒內迅速將半熟爆漿蛋包覆於蔥油餅內，抹上特製蒜蓉甜辣醬。',
        foodInfoEN: 'Fresh dough fried in super hot oil into a blistering puffed pancake, wrapping a runny-yolk egg that bursts upon biting.',
        calories: 410,
        culturalStory: '花蓮復興街聞名全台的排隊名物。高溫猛油瞬間讓餅皮膨起大量香脆氣泡，一口咬下滾燙金黃蛋黃液流淌而出，香氣四溢。',
        texture: '外皮極致酥脆卡滋，內層柔韌帶嚼勁，半熟蛋黃爆漿濃郁。',
        ingredients: ['手工特調低溫發酵麵團', '嚴選產地青蔥', '農場鮮雞蛋', '自熬古法蒜蓉甜辣醬油膏'],
        allergens: ['含蛋製品', '含大豆', '含小麥'],
        cookingMethod: '200度滾油大火快炸，蛋熟蛋白半熟蛋黃，十秒合體出鍋。',
        bestPairing: '咬一口爆漿蛋黃，配一口冰涼現打冬瓜檸檬茶。',
        priceRange: 'NT$ 40 - 55',
        tags: ['花蓮排隊王', '爆漿半熟蛋', '金黃膨脆', '大火炸蛋']
    },
    {
        foodName: '九份阿妹手作三色芋圓地瓜圓嫩仙草',
        foodNameEN: 'Jiufen Handmade Tri-Color Taro & Sweet Potato Balls with Herbal Grass Jelly',
        foodPrice: 60,
        foodType: ['甜點飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        foodInfo: '大甲檳榔心芋頭、台農57號黃金地瓜與紫薯蒸熟純手工捏製揉圓，大水煮滾浮起冰鎮出極致Q彈嚼勁，鋪在關西純天然柴燒嫩仙草凍上，淋上香濃鮮奶油或黑糖水。',
        foodInfoEN: 'Handcrafted chewy taro, sweet potato, and purple yam balls over silky grass jelly, drizzled with sweet cream or brown sugar syrup.',
        calories: 280,
        culturalStory: '九份山城享譽國際的代表性甜品。保留真材實料的地瓜與芋頭顆粒感，冷熱皆宜，已成為台灣各大夜市不可或缺的國民甜品。',
        texture: '芋圓地瓜圓軟Q彈牙帶有真實芋香，仙草如果凍般滑潤清爽。',
        ingredients: ['大甲檳榔心芋泥', '台農57號黃金地瓜', '天然紫薯泥', '純木薯樹薯粉', '新竹關西仙草乾熬製仙草凍'],
        allergens: ['含乳製品 (鮮奶油)'],
        cookingMethod: '生鮮手作芋圓滾水燙熟浮起，入冰水快速冰鎮維持Q彈口感。',
        bestPairing: '可選碎冰黑糖水或熱甜湯，一年四季皆受歡迎。',
        priceRange: 'NT$ 50 - 75',
        tags: ['九份地標', '手工三色圓', 'Q彈嚼勁', '嫩仙草凍']
    },

    // 更多特色麵食與羹湯
    {
        foodName: '宜蘭正宗蒜味肉羹湯',
        foodNameEN: 'Yilan Authentic Heavy Garlic Pork Thick Soup',
        foodPrice: 65,
        foodType: ['傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?auto=format&fit=crop&w=800&q=80',
        foodInfo: '宜蘭代表性傳統老味！整條新鮮溫體黑豬胛心肉手工切條裹薄漿，肉質紮實有咬勁。大鍋羹湯中加入大量爆香生大蒜碎與油蔥，蒜香濃烈撲鼻，勾薄芡酸甜滑順。',
        foodInfoEN: 'Hand-sliced lean pork strips lightly coated in fish paste, served in thick savory broth loaded with fresh crushed garlic and black vinegar.',
        calories: 360,
        culturalStory: '宜蘭雨多濕冷，早期勞動者以重蒜辛香料驅寒提神，進而演變成宜蘭最具特色的「蒜味肉羹」，重蒜香而不辛辣，整條赤肉口感紮實。',
        texture: '肉羹扎實有嚼勁，羹湯滑順帶有極其濃烈爆發的蒜香與烏醋酸甘。',
        ingredients: ['台灣溫體豬胛心赤肉條', '大量雲林在地大蒜碎', '大骨鮮筍高湯', '五印香醋', '特級地瓜粉勾芡'],
        allergens: ['含大豆', '含小麥'],
        cookingMethod: '赤肉醃漬裹漿分次下滾湯燙熟，大蒜慢火爆香入湯勾薄芡。',
        bestPairing: '加麵、加米粉或加粄條，配一份宜蘭卜肉最對味。',
        priceRange: 'NT$ 55 - 75',
        tags: ['宜蘭特色', '蒜香濃烈', '整條赤肉', '重蒜驅寒']
    },
    {
        foodName: '台南正宗紅燒土魠魚羹',
        foodNameEN: 'Tainan Crispy Spanish Mackerel Thick Stew',
        foodPrice: 85,
        foodType: ['海鮮鍋物', '傳統小吃', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?auto=format&fit=crop&w=800&q=80',
        foodInfo: '特選新鮮深海土魠魚切大塊，以大蒜、米酒與特製糖香料醃漬，裹粉高溫炸至外皮金黃酥脆。羹湯以大骨扁魚、大白菜熬煮，勾芡微甜滑順，撒上香菜與胡椒。',
        foodInfoEN: 'Chunky deep-fried marinated Spanish mackerel fillets in sweet cabbage and dried flatfish thick broth with white pepper.',
        calories: 470,
        culturalStory: '台南府城極具代表性的海味羹湯。扁魚白菜羹湯帶有台南特有的甘甜滋味，金黃酥脆的炸土魠魚塊浸在熱湯中半酥半軟，口感妙不可言。',
        texture: '土魠魚塊外皮香脆、肉質扎實鮮甜無刺，羹湯扁魚甘甜滑順。',
        ingredients: ['深海野生土魠魚厚切肉塊', '日曬扁魚乾', '高山甘甜大白菜', '香菜與烏醋', '古早味二砂糖'],
        allergens: ['含魚類', '含小麥', '含大豆'],
        cookingMethod: '土魠魚高溫炸熟瀝油，扁魚爆香入大白菜大骨湯慢熬勾芡，現點現放魚塊。',
        bestPairing: '加台南雞蛋意麵或米粉，酸甜酥嫩一碗打盡。',
        priceRange: 'NT$ 75 - 100',
        tags: ['府城台南味', '酥炸土魠魚', '扁魚白菜羹', '外酥內嫩']
    },
    {
        foodName: '花蓮產地剝皮辣椒土雞湯',
        foodNameEN: 'Hualien Peeled Chili Pepper Free-Range Chicken Soup',
        foodPrice: 110,
        foodType: ['傳統小吃', '海鮮鍋物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=800&q=80',
        foodInfo: '花蓮鳳林與玉里特產綠辣椒油炸去皮醃漬而成之正宗剝皮辣椒！與花蓮放山土雞肉塊、薑片與香菇慢火煨燉，湯頭清甜回甘帶微辛，甘醇不上火。',
        foodInfoEN: 'Tender free-range chicken simmered with signature Hualien pickled green chilies and mushrooms, producing a sweet-spicy soothing broth.',
        calories: 320,
        culturalStory: '花蓮後山依山傍水，產出的綠辣椒炸後去皮泡入醬油甘草汁，脆嫩爽口。煮雞湯時將辣椒醬汁一同入鍋，甜辣溫潤，是花蓮最受推崇的養生名湯。',
        texture: '土雞肉緊緻彈牙，剝皮辣椒爽脆微辛，湯頭清甜甘潤層次分明。',
        ingredients: ['花蓮放山土雞肉塊', '花蓮正宗陳年剝皮辣椒及原汁', '埔里乾香菇', '老薑片', '純釀米酒'],
        allergens: ['含大豆'],
        cookingMethod: '雞肉川燙去血水，與香菇、老薑及剝皮辣椒文火慢熬一小時出味。',
        bestPairing: '搭配原住民竹筒飯或烤香腸，暖胃又舒暢。',
        priceRange: 'NT$ 95 - 130',
        tags: ['花蓮後山', '剝皮辣椒', '放山土雞', '甘甜微辛暖胃']
    },

    // 更多經典炭烤與炸物串燒
    {
        foodName: '炙燒牛肋條骰子牛',
        foodNameEN: 'Flame-Torched Beef Ribeye Cubes with Rose Salt',
        foodPrice: 150,
        foodType: ['烤物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '精選安格斯黑牛肋條厚切成立體骰子方塊，在鐵板上高溫爆炒鎖住肉汁，再以千度高溫瓦斯噴槍猛烈炙燒出焦糖香，撒上喜馬拉雅粉紅玫瑰鹽與粗黑胡椒粒。',
        foodInfoEN: 'Angus beef rib cubes seared on iron griddle and flame-torched with blowtorch, seasoned with Himalayan pink salt and cracked black pepper.',
        calories: 420,
        culturalStory: '近年在全台各大夜市蔚為風潮的視覺系鐵板炙燒小吃，火焰在鐵板上翻騰的火光與陣陣牛油香氣，讓攤位前總是圍滿拍照打卡的饕客。',
        texture: '外層焦香微脆，咬下去牛肉鮮嫩爆汁，牛油香氣濃郁。',
        ingredients: ['頂級安格斯黑牛肋條', '喜馬拉雅粉紅玫瑰岩鹽', '現磨特級粗黑胡椒粒', '大蒜切片', '無鹽發酵奶油'],
        allergens: ['含牛製品', '含乳製品'],
        cookingMethod: '平底高溫鐵板大火快煎定型，噴火槍二次高溫炙燒出梅納反應。',
        bestPairing: '搭配生蒜片或芥末椒鹽，再來一杯現榨生檸檬汁。',
        priceRange: 'NT$ 120 - 180',
        tags: ['噴槍炙燒', '骰子牛爆汁', '玫瑰岩鹽', '夜市打卡秀']
    },
    {
        foodName: '炭烤培根金針菇卷串',
        foodNameEN: 'Charcoal Bacon Wrapped Enoki Mushroom Skewers',
        foodPrice: 50,
        foodType: ['烤物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        foodInfo: '厚切煙燻培根緊緊捲入大把新鮮爽脆金針菇，竹籤穿串於炭火上翻烤，培根油脂滴落炭火激發煙燻香氣，金針菇吸飽肉汁鮮美脆爽，刷上照燒蜜汁醬。',
        foodInfoEN: 'Thick smoky bacon wrapped around bundles of fresh enoki mushrooms, charcoal roasted and glazed with sweet teriyaki sauce.',
        calories: 260,
        culturalStory: '日式居酒屋與台灣夜市結合的人氣串燒，金針菇的多汁中和了培根的鹹膩，葷素搭配完美，是全台各大夜市炭烤攤的必拿爆款。',
        texture: '培根焦脆香濃，金針菇爽脆多汁爆漿，甜鹹炭香交織。',
        ingredients: ['煙燻豬肉培根切片', '新鮮產地金針菇', '特調日式照燒甜醬油', '白芝麻', '七味唐辛子'],
        allergens: ['含大豆', '含芝麻', '含小麥'],
        cookingMethod: '木炭文火慢烤使培根出油緊縮，金針菇軟熟後刷蜜醬撒芝麻。',
        bestPairing: '必配冰涼烏龍茶或生啤酒，下酒絕佳。',
        priceRange: 'NT$ 40 - 60',
        tags: ['炭火串燒', '金針菇爆水', '培根焦脆', '居酒屋風味']
    },
    {
        foodName: '澎湖野生花枝大丸子串',
        foodNameEN: 'Penghu Jumbo Wild Cuttlefish Balls on Skewer',
        foodPrice: 60,
        foodType: ['炸物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
        foodInfo: '100%澎湖產地直送純野生花枝肉手打製作！顆顆碩大如兵乓球，咬開每一口都咬得到整塊鮮脆彈牙的花枝肉丁，油炸至外殼微皺金黃，撒上特級白胡椒鹽。',
        foodInfoEN: 'Giant deep-fried bouncy cuttlefish meatballs stuffed with real chunky calamari pieces, dusted with fragrant white pepper salt.',
        calories: 290,
        culturalStory: '澎湖外海海流湍急，花枝肉質極具彈性。澎湖正宗花枝丸標榜「每一口都吃得到花枝塊」，不摻雜廉價雜魚漿，是海島夜市與各觀光景點最受歡迎的零嘴。',
        texture: '外皮金黃微脆，丸體極致彈牙Q脆，花枝肉塊鮮嫩多汁。',
        ingredients: ['澎湖野生新鮮深海大花枝肉', '新鮮花枝漿', '特級白胡椒粉', '自製純蒜香椒鹽'],
        allergens: ['含軟體動物花枝'],
        cookingMethod: '手工捏圓水煮定型，高溫油鍋快速油炸至外殼金黃鼓起。',
        bestPairing: '直接拿著竹籤邊逛邊吃，沾少許檸檬汁更鮮甜。',
        priceRange: 'NT$ 50 - 70',
        tags: ['澎湖特產', '整塊花枝肉', '爆彈Q脆', '人手一串']
    },
    {
        foodName: '夜市炸鮮奶球',
        foodNameEN: 'Deep-Fried Molten Crispy Fresh Milk Balls',
        foodPrice: 50,
        foodType: ['甜點飲品', '炸物', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        foodInfo: '新鮮濃醇鮮乳與玉米粉、糖慢火熬煮成綿密奶凍，冷藏定型後切塊穿串，裹上特調金黃脆皮麵衣高溫快速油炸，外皮酥脆滾燙，內餡如布丁般滑順爆漿融化。',
        foodInfoEN: 'Bite-sized cubes of chilled sweet milk custard coated in batter and flash-fried crispy, with a molten, creamy center.',
        calories: 330,
        culturalStory: '源自廣東順德名菜大良炸鮮奶，傳入台灣夜市後改版為竹籤小巧串裝。外酥內爆漿的冷熱反差口感與純濃奶香，深受大小朋友熱愛。',
        texture: '外皮薄脆輕盈，內餡滾燙絲滑如流心牛奶布丁，奶香濃郁。',
        ingredients: ['台灣產銷鮮純鮮乳', '天然非基改玉米澱粉', '細白砂糖', '無水奶油', '脆皮酥漿粉'],
        allergens: ['含牛奶/乳製品', '含小麥'],
        cookingMethod: '奶糊冷藏凝固切方塊穿籤，裹薄漿入180度油鍋快炸30秒搶酥。',
        bestPairing: '稍微吹涼趁熱食用，配無糖茶飲絕配。',
        priceRange: 'NT$ 40 - 60',
        tags: ['外酥內爆漿', '流心鮮奶', '大小朋友最愛', '濃醇香滑']
    },

    // 更多手搖與經典冰飲
    {
        foodName: '大甲芋頭控必喝鮮奶',
        foodNameEN: 'Dajia Taro Puree with Rich Whole Milk',
        foodPrice: 70,
        foodType: ['飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1558857563-b37cf5b7a151?auto=format&fit=crop&w=800&q=80',
        foodInfo: '台中大甲產地直送檳榔心芋頭，慢火蒸熟後加入二砂糖手工打成帶有顆粒感與絲滑泥狀的濃稠蜜芋泥，半杯滿滿芋泥倒入100%全脂冰鮮乳，濃郁厚實無比。',
        foodInfoEN: 'Freshly mashed Dajia sweet taro paste loaded halfway into the cup, filled with 100% whole fresh milk, creamy and natural.',
        calories: 390,
        culturalStory: '大甲因大安溪水源與黑沙土壤，培育出全台灣香氣最濃、質地最鬆綿的大甲芋頭。夜市芋頭鮮奶堅持不用人工香精，純天然芋泥讓芋頭控欲罷不能。',
        texture: '吸得到鬆軟綿密的芋頭碎粒與絲滑芋泥，與濃純鮮乳完美交融。',
        ingredients: ['台中大甲檳榔心純芋頭', '天然二砂糖', '單一牧場全脂純鮮乳'],
        allergens: ['含牛奶/乳製品'],
        cookingMethod: '芋頭蒸透趁熱壓泥加糖拌炒，杯中鋪滿手打芋泥倒入冰鮮奶。',
        bestPairing: '飲用前上下搖勻，配一份剛出爐的脆皮地瓜球。',
        priceRange: 'NT$ 65 - 85',
        tags: ['大甲芋頭', '真材實料', '半杯芋泥', '芋頭控天堂']
    },
    {
        foodName: '燕巢芭樂配古坑柳丁無水現打汁',
        foodNameEN: 'Cold-Pressed Guava & Orange Fresh Fruit Juice',
        foodPrice: 65,
        foodType: ['飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        foodInfo: '高雄燕巢新鮮清脆珍珠芭樂，搭配雲林古坑香甜多汁老欉柳丁，整顆現切不加一滴水、不加糖，高速慢磨壓榨出百分之百純天然蔬果維他命C精華。',
        foodInfoEN: '100% pure cold-pressed juice of crispy Yanchao guavas and sweet Gukeng oranges, with zero added water or sugar.',
        calories: 150,
        culturalStory: '台灣夜市經典現榨果汁攤的代表之作。台灣有水果王國美譽，芭樂的特殊果香與柳丁的酸甜柑橘香氣是台灣人從小喝到大的經典雙果搭檔。',
        texture: '果泥微帶細緻纖維感，口感濃醇甘甜，純天然果香令人神清氣爽。',
        ingredients: ['高雄燕巢新鮮珍珠芭樂', '雲林古坑產地直送甜柳橙', '純過濾碎冰'],
        allergens: [],
        cookingMethod: '新鮮水果去籽切塊，高速蔬果慢磨機無水冷壓榨汁。',
        bestPairing: '吃完油炸雞排或炭烤串燒後的最佳天然解膩清腸排毒果汁。',
        priceRange: 'NT$ 60 - 80',
        tags: ['水果王國', '不加一滴水', '滿滿維他命C', '天然鮮甜']
    },
    {
        foodName: '新竹北埔客家現磨擂茶拿鐵',
        foodNameEN: 'Beipu Hakka Ground Leicha Tea Latte',
        foodPrice: 60,
        foodType: ['飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1558857563-b37cf5b7a151?auto=format&fit=crop&w=800&q=80',
        foodInfo: '新竹北埔客家傳統手藝！將綠茶葉、芝麻、花生、松子與二十多種五穀雜糧在擂缽中研磨成細緻微香茶粉，沖入高山熱茶與純濃鮮奶，撒上香脆玄米粒。',
        foodInfoEN: 'Traditional Hakka tea ground from green tea leaves, sesame, roasted peanuts, and 20 multi-grains, brewed with fresh milk and puffed brown rice.',
        calories: 240,
        culturalStory: '客家人招待貴賓的古老茶禮「擂茶」，已有上千年歷史。經過現代手搖茶飲改良，融入鮮奶與玄米，兼具五穀養生飽足感與手搖茶的芳香順口。',
        texture: '茶湯溫潤醇厚帶有堅果穀物香氣，玄米脆粒增添咀嚼驚喜。',
        ingredients: ['北埔產地綠茶粉', '熟黑白芝麻與花生', '綜合二十四種天然五穀粉', '台灣小農純鮮乳', '香酥炒玄米粒'],
        allergens: ['含花生', '含芝麻', '含堅果', '含牛奶/乳製品'],
        cookingMethod: '堅果五穀手工細擂磨粉，熱水沖調乳化後加入冰鮮乳與玄米。',
        bestPairing: '搭配牛舌餅、太陽餅或客家麻糬，體驗最悠閒的茶點時光。',
        priceRange: 'NT$ 55 - 75',
        tags: ['客家擂茶', '二十四種五穀', '養生飽足', '擂茶拿鐵']
    },
    {
        foodName: '澎湖野生風茹退火青草茶',
        foodNameEN: 'Penghu Wild Fong-Ru Herbal Cleansing Tea',
        foodPrice: 40,
        foodType: ['飲品', '人氣必吃'],
        foodIcon: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        foodInfo: '澎湖海島特有野生藥草「風茹草」（澎湖香草）！在澎湖強烈海風與艷陽下日曬乾燥，慢火熬煮出深琥珀色茶湯，微甜回甘、草本清香撲鼻，完全不苦澀。',
        foodInfoEN: 'Herbal cooling tea brewed from wild Penghu Fong-Ru coastal grass, naturally sweet with earthy minty notes, perfect for beating the heat.',
        calories: 80,
        culturalStory: '風茹草被譽為「澎湖青草茶之王」，是澎湖人百年來抵禦烈日烈火的退火秘方。富含微量元素與抗氧化物，味道清香甘甜，被列為澎湖三寶之一。',
        texture: '茶湯清澈冰涼，入口甘潤生津，帶有薄荷與清草的微涼回甘芳香。',
        ingredients: ['澎湖野生天然日曬風茹全草', '古法純二砂糖', '純淨甘甜過濾水'],
        allergens: [],
        cookingMethod: '乾風茹草洗淨，慢火水煮一小時萃取草本精華，微糖冰鎮。',
        bestPairing: '在炎熱夜市逛街揮汗時一口飲下，瞬間消暑退火解渴。',
        priceRange: 'NT$ 35 - 50',
        tags: ['澎湖三寶', '風茹茶王', '海島解暑', '清涼回甘不苦']
    }
];

module.exports = {
    ADDITIONAL_TAIWAN_FOODS
};
